/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Distributor;

import Business.Enterprise.CDCEnterprise;
import Business.Enterprise.NationalDistributorEnterprise;
import Business.Network.Network;
import Business.Organization.Distributor.DistributionCentre;
import Business.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rishika Idnani
 */
public class DistributorWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form DistributorWorkArea
     */
    private JPanel userProcessContainer;
    private NationalDistributorEnterprise nationalDistributorEnterprise;
    private CDCEnterprise cdcEnterprise;
    private Network network;

    public DistributorWorkArea(JPanel userProcessContainer, NationalDistributorEnterprise nationalDistributorEnterprise,
            CDCEnterprise cdcEnterprise, Network network) {
        initComponents();
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.nationalDistributorEnterprise = nationalDistributorEnterprise;
        this.cdcEnterprise = cdcEnterprise;
        this.network = network;

        structureInternalFrame();
        populateStateComboBox();
        populateTable();
    }

    public void structureInternalFrame() {
        javax.swing.plaf.InternalFrameUI warehouseFrameUI = warehouseJInternalFrame.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) warehouseFrameUI).setNorthPane(null);
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) warehouseJTable.getModel();
        model.setRowCount(0);

        for (Organization o : nationalDistributorEnterprise.getOrganizationDirectory().getOrganizationList()) {
            if (o instanceof DistributionCentre) {
                DistributionCentre org = (DistributionCentre) o;
                Object row[] = new Object[3];
                row[0] = org;
                row[1] = org.getStateName();
                row[2] = org.getPinCode();
                model.addRow(row);
            }
        }
    }

    public void populateStateComboBox() {
        stateJComboBox.removeAllItems();;

        stateJComboBox.addItem("");
        stateJComboBox.addItem("California");
        stateJComboBox.addItem("Florida");
        stateJComboBox.addItem("Illinois");
        stateJComboBox.addItem("Maryland");
        stateJComboBox.addItem("Massachusetts");
        stateJComboBox.addItem("New York");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelDescriptionJLabel = new javax.swing.JLabel();
        viewOrdersJButton = new javax.swing.JButton();
        warehouseJInternalFrame = new javax.swing.JInternalFrame();
        addJLabel = new javax.swing.JLabel();
        chooseJLabel = new javax.swing.JLabel();
        stateJComboBox = new javax.swing.JComboBox();
        addJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pinJComboBox = new javax.swing.JComboBox();
        nameJLabel = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        addUserJButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        warehouseJTable = new javax.swing.JTable();
        removeJButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        panelDescriptionJLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelDescriptionJLabel.setText("Distributor Work Area");

        viewOrdersJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        viewOrdersJButton.setText("Track Orders >>");
        viewOrdersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrdersJButtonActionPerformed(evt);
            }
        });

        warehouseJInternalFrame.setVisible(true);

        addJLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        addJLabel.setText("Add Distribution Warehouse");

        chooseJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        chooseJLabel.setText("Choose State:");

        stateJComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        stateJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        stateJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateJComboBoxActionPerformed(evt);
            }
        });

        addJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addJButton.setText("Add Centre");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Pin code:");

        pinJComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pinJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        nameJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nameJLabel.setText("Name");

        nameJTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout warehouseJInternalFrameLayout = new javax.swing.GroupLayout(warehouseJInternalFrame.getContentPane());
        warehouseJInternalFrame.getContentPane().setLayout(warehouseJInternalFrameLayout);
        warehouseJInternalFrameLayout.setHorizontalGroup(
            warehouseJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warehouseJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warehouseJInternalFrameLayout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(warehouseJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warehouseJInternalFrameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addJButton))
                    .addGroup(warehouseJInternalFrameLayout.createSequentialGroup()
                        .addGroup(warehouseJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(chooseJLabel)
                            .addComponent(nameJLabel))
                        .addGap(18, 18, 18)
                        .addGroup(warehouseJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stateJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pinJComboBox, 0, 143, Short.MAX_VALUE)
                            .addComponent(nameJTextField))
                        .addGap(74, 74, 74)))
                .addGap(48, 48, 48))
        );
        warehouseJInternalFrameLayout.setVerticalGroup(
            warehouseJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warehouseJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addJLabel)
                .addGap(27, 27, 27)
                .addGroup(warehouseJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameJLabel)
                    .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(warehouseJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseJLabel)
                    .addComponent(stateJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(warehouseJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pinJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addJButton)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Display of States where warehouse is present");

        addUserJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addUserJButton.setText("Manage Distribution Centre User Account >>");
        addUserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserJButtonActionPerformed(evt);
            }
        });

        warehouseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Distribution Warehouse Name", "State", "Pin Code"
            }
        ));
        warehouseJTable.setRowHeight(25);
        jScrollPane3.setViewportView(warehouseJTable);

        removeJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        removeJButton.setText("Remove Warehouse");
        removeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(warehouseJInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDescriptionJLabel)
                    .addComponent(addUserJButton)
                    .addComponent(viewOrdersJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(removeJButton)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDescriptionJLabel)
                .addGap(28, 28, 28)
                .addComponent(viewOrdersJButton)
                .addGap(35, 35, 35)
                .addComponent(warehouseJInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeJButton))
                .addGap(32, 32, 32)
                .addComponent(addUserJButton)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewOrdersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrdersJButtonActionPerformed
        // TODO add your handling code here:
        TrackVaccineOrders panel = new TrackVaccineOrders(userProcessContainer, cdcEnterprise, nationalDistributorEnterprise);

        userProcessContainer.add("ViewOrders", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewOrdersJButtonActionPerformed

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        // TODO add your handling code here:
        String stateName = String.valueOf(stateJComboBox.getSelectedItem());
        int pinCode;
        String name = nameJTextField.getText();
        try {
            pinCode = Integer.parseInt(String.valueOf(pinJComboBox.getSelectedItem()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Kindly input pin code!");
            return;
        }
        if (stateName.trim().equals("") || name.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Kindly input proper values!");
            return;
        }

        DistributionCentre organization = nationalDistributorEnterprise.getOrganizationDirectory().addDistributionCentre(Organization.TypeOfOrganization.Admin, stateName, pinCode, name);
        if (organization == null) {
            JOptionPane.showMessageDialog(null, "Distribution centre already exist!");
            return;
        }
        populateTable();
        stateJComboBox.setSelectedIndex(0);
        pinJComboBox.setSelectedIndex(0);
        nameJTextField.setText("");
    }//GEN-LAST:event_addJButtonActionPerformed

    private void addUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserJButtonActionPerformed
        // TODO add your handling code here:
        ManageUserAccount panel = new ManageUserAccount(userProcessContainer, nationalDistributorEnterprise, network);

        userProcessContainer.add("ManageAccount", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addUserJButtonActionPerformed

    private void stateJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateJComboBoxActionPerformed
        // TODO add your handling code here:
        String stateName = String.valueOf(stateJComboBox.getSelectedItem());
        pinJComboBox.removeAllItems();

        if (stateName.equals("California")) {
            pinJComboBox.addItem("90211");
        } else if (stateName.equals("Florida")) {
            pinJComboBox.addItem("32201");
        } else if (stateName.equals("Illinois")) {
            pinJComboBox.addItem("60001");
        } else if (stateName.equals("Maryland")) {
            pinJComboBox.addItem("21741");
        } else if (stateName.equals("Massachusetts")) {
            pinJComboBox.addItem("02121");
            pinJComboBox.addItem("02127");
        } else if (stateName.equals("New York")) {
            pinJComboBox.addItem("10002");
        } else if (stateName.equals("")) {
            pinJComboBox.addItem("");
        }
    }//GEN-LAST:event_stateJComboBoxActionPerformed

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = warehouseJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Kindly select the warehouse");
            return;
        }

        DistributionCentre distributionCentre = (DistributionCentre) warehouseJTable.getValueAt(selectedRow, 0);

        nationalDistributorEnterprise.getOrganizationDirectory().removeOrganization(distributionCentre);
        populateTable();
    }//GEN-LAST:event_removeJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JLabel addJLabel;
    private javax.swing.JButton addUserJButton;
    private javax.swing.JLabel chooseJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JLabel panelDescriptionJLabel;
    private javax.swing.JComboBox pinJComboBox;
    private javax.swing.JButton removeJButton;
    private javax.swing.JComboBox stateJComboBox;
    private javax.swing.JButton viewOrdersJButton;
    private javax.swing.JInternalFrame warehouseJInternalFrame;
    private javax.swing.JTable warehouseJTable;
    // End of variables declaration//GEN-END:variables
}
