/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.VaccineManufacturer;

import Business.Ecosystem;
import Business.Enterprise.CDCEnterprise;
import Business.Enterprise.PHDEnterprise;
import Business.Enterprise.VaccineManufacturerEnterprise;
import Business.Vaccine.Disease;
import Business.Vaccine.Vaccine;
import java.awt.CardLayout;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rishika Idnani
 */
public class AddVaccines extends javax.swing.JPanel {

    /**
     * Creates new form AddVaccines
     */
    private JPanel userProcessContainer;
    private VaccineManufacturerEnterprise enterprise;
    private Ecosystem system;
    private CDCEnterprise cdcEnterprise;

    public AddVaccines(JPanel userProcessContainer, VaccineManufacturerEnterprise enterprise, CDCEnterprise cdcEnterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.cdcEnterprise = cdcEnterprise;

        structureInternalFrame();
        populateDiseaseJComboBox();
        populateVaccineTable();
    }

    public void structureInternalFrame() {
        javax.swing.plaf.InternalFrameUI vaccineFrameUI = vaccineJInternalFrame.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) vaccineFrameUI).setNorthPane(null);
    }

    public void populateDiseaseJComboBox() {
        diseaseJComboBox.removeAllItems();

        for (Disease disease : cdcEnterprise.getDiseaseCatalog().getDiseaseList()) {
            diseaseJComboBox.addItem(disease);
        }
    }

    public void populateVaccineTable() {
        DefaultTableModel model = (DefaultTableModel) vaccineJTable.getModel();
        model.setRowCount(0);

        for (Vaccine vaccine : enterprise.getVaccineCatalog().getVaccineList()) {
            Object row[] = new Object[4];
            row[0] = vaccine;
            row[1] = vaccine.getSerialNo();
            row[2] = vaccine.getPrice();
            row[3] = vaccine.getDisease();
            model.addRow(row);
        }
    }

    public Date getTodaysDate() {
        Date manufacturingDate = new Date();
        return manufacturingDate;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDescriptionJLabel = new javax.swing.JLabel();
        displayOfVaccineJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vaccineJTable = new javax.swing.JTable();
        removeVaccine = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        vaccineJInternalFrame = new javax.swing.JInternalFrame();
        vaccineNameJLabel = new javax.swing.JLabel();
        addVaccineJLabel = new javax.swing.JLabel();
        vaccinePriceJLabel = new javax.swing.JLabel();
        diseaseJLabel = new javax.swing.JLabel();
        diseaseJComboBox = new javax.swing.JComboBox();
        vaccinePriceJTextField = new javax.swing.JTextField();
        vaccineNameJTextField = new javax.swing.JTextField();
        addVaccineJButton = new javax.swing.JButton();
        timeJLabel = new javax.swing.JLabel();
        timeJTextField = new javax.swing.JTextField();
        validityJLabel = new javax.swing.JLabel();
        validityJTextField = new javax.swing.JTextField();

        panelDescriptionJLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelDescriptionJLabel.setText("Manage Vaccine Catalog");

        displayOfVaccineJLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        displayOfVaccineJLabel.setText("Display of Vaccines");

        vaccineJTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        vaccineJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Vaccine Name", "Vaccine Serial Number", "Vaccine Price", "Disease"
            }
        ));
        vaccineJTable.setRowHeight(25);
        jScrollPane1.setViewportView(vaccineJTable);

        removeVaccine.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        removeVaccine.setText("Remove Vaccine");
        removeVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeVaccineActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        vaccineJInternalFrame.setVisible(true);

        vaccineNameJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        vaccineNameJLabel.setText("Vaccine Name");

        addVaccineJLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addVaccineJLabel.setText("Add Vaccine");

        vaccinePriceJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        vaccinePriceJLabel.setText("Vaccine Price");

        diseaseJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        diseaseJLabel.setText("Disease");

        diseaseJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        vaccinePriceJTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        vaccineNameJTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        addVaccineJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addVaccineJButton.setText("Add Vaccine");
        addVaccineJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVaccineJButtonActionPerformed(evt);
            }
        });

        timeJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        timeJLabel.setText("Time required for manufactuirng(in days)");

        validityJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        validityJLabel.setText("Validity(in days)");

        javax.swing.GroupLayout vaccineJInternalFrameLayout = new javax.swing.GroupLayout(vaccineJInternalFrame.getContentPane());
        vaccineJInternalFrame.getContentPane().setLayout(vaccineJInternalFrameLayout);
        vaccineJInternalFrameLayout.setHorizontalGroup(
            vaccineJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vaccineJInternalFrameLayout.createSequentialGroup()
                .addGroup(vaccineJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vaccineJInternalFrameLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(vaccineJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vaccineNameJLabel)
                            .addComponent(vaccinePriceJLabel)
                            .addComponent(diseaseJLabel))
                        .addGap(43, 43, 43)
                        .addGroup(vaccineJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vaccineNameJTextField)
                            .addComponent(vaccinePriceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diseaseJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addVaccineJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(vaccineJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeJLabel)
                            .addComponent(validityJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(vaccineJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(validityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(vaccineJInternalFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addVaccineJLabel)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        vaccineJInternalFrameLayout.setVerticalGroup(
            vaccineJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vaccineJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addVaccineJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(vaccineJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vaccineNameJLabel)
                    .addComponent(vaccineNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeJLabel)
                    .addComponent(timeJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(vaccineJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vaccinePriceJLabel)
                    .addComponent(vaccinePriceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validityJLabel)
                    .addComponent(validityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(vaccineJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diseaseJLabel)
                    .addComponent(diseaseJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(addVaccineJButton)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelDescriptionJLabel)
                                    .addComponent(displayOfVaccineJLabel)
                                    .addComponent(vaccineJInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 116, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(removeVaccine)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDescriptionJLabel)
                .addGap(27, 27, 27)
                .addComponent(vaccineJInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(displayOfVaccineJLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(removeVaccine))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addVaccineJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVaccineJButtonActionPerformed
        // TODO add your handling code here:
        String vaccineName = vaccineNameJTextField.getText();
        Disease disease = (Disease) diseaseJComboBox.getSelectedItem();
        int price;
        int time;
        int validity;

        try {
            price = Integer.parseInt(vaccinePriceJTextField.getText());
            time = Integer.parseInt(timeJTextField.getText());
            validity = Integer.parseInt(validityJTextField.getText());
            if (vaccineName.trim().equals("")
                    || price == 0 || price < 0
                    || disease == null
                    || time < 0
                    || time == 0
                    || validity == 0 || validity < 0) {
                throw new Exception();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please enter proper values");
            return;
        }
        Vaccine vaccine = enterprise.getVaccineCatalog().addAndCreateVaccine(vaccineName, price, disease, time, validity, enterprise);
        vaccineNameJTextField.setText("");
        vaccinePriceJTextField.setText("");
        timeJTextField.setText("");
        validityJTextField.setText("");
        diseaseJComboBox.setSelectedItem(0);
        populateVaccineTable();
    }//GEN-LAST:event_addVaccineJButtonActionPerformed

    private void removeVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeVaccineActionPerformed
        // TODO add your handling code here:
        int selectedRow = vaccineJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the row");
            return;
        }

        Vaccine vaccine = (Vaccine) vaccineJTable.getValueAt(selectedRow, 0);
        enterprise.getVaccineCatalog().removeVaccine(vaccine);
        populateVaccineTable();
    }//GEN-LAST:event_removeVaccineActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVaccineJButton;
    private javax.swing.JLabel addVaccineJLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox diseaseJComboBox;
    private javax.swing.JLabel diseaseJLabel;
    private javax.swing.JLabel displayOfVaccineJLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel panelDescriptionJLabel;
    private javax.swing.JButton removeVaccine;
    private javax.swing.JLabel timeJLabel;
    private javax.swing.JTextField timeJTextField;
    private javax.swing.JInternalFrame vaccineJInternalFrame;
    private javax.swing.JTable vaccineJTable;
    private javax.swing.JLabel vaccineNameJLabel;
    private javax.swing.JTextField vaccineNameJTextField;
    private javax.swing.JLabel vaccinePriceJLabel;
    private javax.swing.JTextField vaccinePriceJTextField;
    private javax.swing.JLabel validityJLabel;
    private javax.swing.JTextField validityJTextField;
    // End of variables declaration//GEN-END:variables
}
