/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.VaccineManufacturer;

import Business.Enterprise.CDCEnterprise;
import Business.Enterprise.PHDEnterprise;
import Business.Enterprise.VaccineManufacturerEnterprise;
import Business.Vaccine.Vaccine;
import Business.Vaccine.VaccineAllocation;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rishika Idnani
 */
public class ManageVaccineInventory extends javax.swing.JPanel {

    /**
     * Creates new form ManageVaccineInventory
     */
    private JPanel userProcessContainer;
    private VaccineManufacturerEnterprise enterprise;
    private CDCEnterprise cdcEnterprise;

    public ManageVaccineInventory(JPanel userProcessContainer, VaccineManufacturerEnterprise enterprise, CDCEnterprise cdcEnterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.cdcEnterprise = cdcEnterprise;

        structureInternalFrame();
        populateTable();
        populateVaccineTable();
    }

    public void structureInternalFrame() {
        javax.swing.plaf.InternalFrameUI availableFrameUI = availableJInternalFrame.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) availableFrameUI).setNorthPane(null);
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) vaccineAvailableJTable.getModel();
        model.setRowCount(0);

        for (Vaccine vaccine : enterprise.getVaccineInventory().getVaccineInventoryList()) {
            if (vaccine.getBatchAvailability() > 0) {
                Object row[] = new Object[4];
                row[0] = vaccine;
                row[1] = vaccine.getBatchAvailability();
                row[2] = vaccine.getManufacturingBatch();
                row[3] = vaccine.getExpiryDate();
                model.addRow(row);
            }
        }
    }

    public void populateVaccineTable() {
        DefaultTableModel model = (DefaultTableModel) vaccineJTable.getModel();
        model.setRowCount(0);

        for (Vaccine vaccine : enterprise.getVaccineCatalog().getVaccineList()) {
            Object row[] = new Object[4];
            row[0] = vaccine;
            row[1] = vaccine.getSerialNo();
            row[2] = vaccine.getPrice();
            model.addRow(row);
        }
    }

    public void populateVaccineAvailableTable(Vaccine vaccineForSale) {
        DefaultTableModel model = (DefaultTableModel) vaccineAvailableJTable.getModel();

//        for (Vaccine vaccine : enterprise.getVaccineInventory().getVaccineInventoryList()) {
//            if (vaccine.getName().equals(vaccineForSale.getName())) {
        Object row[] = new Object[4];
        row[0] = vaccineForSale;
        row[1] = vaccineForSale.getBatchAvailability();
        row[2] = vaccineForSale.getManufacturingBatch();
        row[3] = vaccineForSale.getExpiryDate();
        model.addRow(row);
//            }
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDescriptionJLabel = new javax.swing.JLabel();
        vaccineJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vaccineJTable = new javax.swing.JTable();
        availableJInternalFrame = new javax.swing.JInternalFrame();
        createJLabel = new javax.swing.JLabel();
        availableJLabel = new javax.swing.JLabel();
        availableJTextField = new javax.swing.JTextField();
        setJButton = new javax.swing.JButton();
        displayJLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        vaccineAvailableJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();

        panelDescriptionJLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelDescriptionJLabel.setText("Manage Vaccine Inventory");

        vaccineJLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        vaccineJLabel.setText("Vaccine Catalog");

        vaccineJTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        vaccineJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Vaccine Name", "Vaccine Serial Number", "Price"
            }
        ));
        vaccineJTable.setRowHeight(25);
        jScrollPane1.setViewportView(vaccineJTable);

        availableJInternalFrame.setVisible(true);

        createJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        createJLabel.setText("Create new batch");

        availableJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        availableJLabel.setText("Availability");

        availableJTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        setJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setJButton.setText("Set");
        setJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout availableJInternalFrameLayout = new javax.swing.GroupLayout(availableJInternalFrame.getContentPane());
        availableJInternalFrame.getContentPane().setLayout(availableJInternalFrameLayout);
        availableJInternalFrameLayout.setHorizontalGroup(
            availableJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(availableJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(availableJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(availableJLabel)
                    .addComponent(createJLabel))
                .addGap(29, 29, 29)
                .addComponent(availableJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, availableJInternalFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(setJButton)
                .addGap(37, 37, 37))
        );
        availableJInternalFrameLayout.setVerticalGroup(
            availableJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(availableJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createJLabel)
                .addGap(18, 18, 18)
                .addGroup(availableJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availableJLabel)
                    .addComponent(availableJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(setJButton)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        displayJLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        displayJLabel.setText("Display of Inventory");

        vaccineAvailableJTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        vaccineAvailableJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Vaccine Name", "Vaccine Availability", "Manufacturing Batch", "Expiry Date"
            }
        ));
        vaccineAvailableJTable.setRowHeight(25);
        jScrollPane2.setViewportView(vaccineAvailableJTable);

        backJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(availableJInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelDescriptionJLabel)
                            .addComponent(vaccineJLabel)
                            .addComponent(displayJLabel)
                            .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDescriptionJLabel)
                .addGap(18, 18, 18)
                .addComponent(vaccineJLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(availableJInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(displayJLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(backJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setJButtonActionPerformed
        // TODO add your handling code here:
        int vaccineAvailability;
        try {
            vaccineAvailability = Integer.parseInt(availableJTextField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Kindly input proper values");
            return;
        }

        int selectedRow = vaccineJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Kindly select a row");
            return;
        }

        Vaccine vaccine = (Vaccine) vaccineJTable.getValueAt(selectedRow, 0);
        Vaccine vaccineForSale = enterprise.getVaccineInventory().addVaccineInInventory(vaccine, vaccineAvailability);
        availableJTextField.setText("");
        populateVaccineAvailableTable(vaccineForSale);

//*************Set state level allocation******************
        ArrayList<VaccineAllocation> vaccineAllocationData = vaccineForSale.getVaccineAllocationData();
        vaccineAllocationData = new ArrayList<>();
        vaccineForSale.setVaccineAllocationData(vaccineAllocationData);
        for (PHDEnterprise phdEnterprise : cdcEnterprise.getPhdList()) {
            float populationPercentile = phdEnterprise.setAllocatedPercentileForState(phdEnterprise.getStateName());
            float allocatedQuantity = (populationPercentile / 100) * vaccineAvailability;
            VaccineAllocation vaccineAllocation = new VaccineAllocation();
            vaccineAllocation.setPhdEnterprise(phdEnterprise);
            vaccineAllocation.setAllocatedVaccineQuantity(allocatedQuantity);
            vaccineAllocationData.add(vaccineAllocation);
        }
//*******************************************************************
    }//GEN-LAST:event_setJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame availableJInternalFrame;
    private javax.swing.JLabel availableJLabel;
    private javax.swing.JTextField availableJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel createJLabel;
    private javax.swing.JLabel displayJLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel panelDescriptionJLabel;
    private javax.swing.JButton setJButton;
    private javax.swing.JTable vaccineAvailableJTable;
    private javax.swing.JLabel vaccineJLabel;
    private javax.swing.JTable vaccineJTable;
    // End of variables declaration//GEN-END:variables
}
