/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.VaccineManufacturer;

import Business.Enterprise.CDCEnterprise;
import Business.Enterprise.VaccineManufacturerEnterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Rishika Idnani
 */
public class VaccineManufacturerWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form VaccineManufacturerWorkArea
     */
    private JPanel userProcessContainer;
    private VaccineManufacturerEnterprise enterprise;
    private CDCEnterprise cdcEnterprise;

    public VaccineManufacturerWorkArea(JPanel userProcessContainer, VaccineManufacturerEnterprise enterprise, CDCEnterprise cdcEnterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.cdcEnterprise = cdcEnterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDescriptionJLabel = new javax.swing.JLabel();
        addVaccinesJButton = new javax.swing.JButton();
        viewVaccinesJButton = new javax.swing.JButton();
        trackJButton = new javax.swing.JButton();
        manageInventoryJButton = new javax.swing.JButton();

        panelDescriptionJLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelDescriptionJLabel.setText("Vaccine Manufacturer Work Area");

        addVaccinesJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addVaccinesJButton.setText("Add Vaccines >>");
        addVaccinesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVaccinesJButtonActionPerformed(evt);
            }
        });

        viewVaccinesJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        viewVaccinesJButton.setText("View Vaccine Orders >>");
        viewVaccinesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVaccinesJButtonActionPerformed(evt);
            }
        });

        trackJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        trackJButton.setText("Track Vaccine Wastage >>");
        trackJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackJButtonActionPerformed(evt);
            }
        });

        manageInventoryJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        manageInventoryJButton.setText("Manage Inventory >>");
        manageInventoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageInventoryJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDescriptionJLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(manageInventoryJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(trackJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addVaccinesJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewVaccinesJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDescriptionJLabel)
                .addGap(28, 28, 28)
                .addComponent(addVaccinesJButton)
                .addGap(18, 18, 18)
                .addComponent(manageInventoryJButton)
                .addGap(18, 18, 18)
                .addComponent(viewVaccinesJButton)
                .addGap(18, 18, 18)
                .addComponent(trackJButton)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addVaccinesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVaccinesJButtonActionPerformed
        // TOaDO add your handling code here:
        AddVaccines panel = new AddVaccines(userProcessContainer, enterprise, cdcEnterprise);

        userProcessContainer.add("AddVaccines", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addVaccinesJButtonActionPerformed

    private void viewVaccinesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVaccinesJButtonActionPerformed
        // TODO add your handling code here:
        ViewOrders panel = new ViewOrders(userProcessContainer, enterprise, cdcEnterprise);

        userProcessContainer.add("ViewOrders", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewVaccinesJButtonActionPerformed

    private void manageInventoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageInventoryJButtonActionPerformed
        // TODO add your handling code here:
        ManageVaccineInventory panel = new ManageVaccineInventory(userProcessContainer, enterprise, cdcEnterprise);

        userProcessContainer.add("ManageInventory", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageInventoryJButtonActionPerformed

    private void trackJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackJButtonActionPerformed
        // TODO add your handling code here:
        TrackVaccineWastage panel = new TrackVaccineWastage(userProcessContainer, enterprise, cdcEnterprise);

        userProcessContainer.add("VaccineWastage", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_trackJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVaccinesJButton;
    private javax.swing.JButton manageInventoryJButton;
    private javax.swing.JLabel panelDescriptionJLabel;
    private javax.swing.JButton trackJButton;
    private javax.swing.JButton viewVaccinesJButton;
    // End of variables declaration//GEN-END:variables
}
