/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CentreForDiseaseControl;

import Business.Enterprise.CDCEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PHDEnterprise;
import Business.Enterprise.VaccineManufacturerEnterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rishika Idnani
 */
public class AddPhdAndManufacturer extends javax.swing.JPanel {

    /**
     * Creates new form AddPhdAndManufacturer
     */
    private JPanel userProcessContainer;
    private CDCEnterprise enterprise;
    private Network network;

    public AddPhdAndManufacturer(JPanel userProcessContainer, CDCEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.network = enterprise.getNetwork();
        structureInternalFrame();
        populateEnterpriseTypeComboBox();
        populateStateComboBox();
        populateEnterpriseTable();
    }

    public void structureInternalFrame() {
        javax.swing.plaf.InternalFrameUI phdFrameUI = phdJInternalFrame.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) phdFrameUI).setNorthPane(null);
    }

    public void populateEnterpriseTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseJTable.getModel();
        model.setRowCount(0);

        for (PHDEnterprise enterprise : enterprise.getPhdList()) {
            Object row[] = new Object[3];
            row[0] = enterprise.getTypeOfEnterprise();
            row[1] = enterprise;
            row[2] = enterprise.getStateName();
            model.addRow(row);
        }

        for (VaccineManufacturerEnterprise enterprise : enterprise.getVaccineManufacturerList()) {
            Object row[] = new Object[3];
            row[0] = enterprise.getTypeOfEnterprise();
            row[1] = enterprise;
            row[2] = "Not Applicable";
            model.addRow(row);
        }
    }

    public void populateStateComboBox() {
        stateJComboBox.removeAllItems();;

        stateJComboBox.addItem("");
        stateJComboBox.addItem("California");
        stateJComboBox.addItem("Florida");
        stateJComboBox.addItem("Illinois");
        stateJComboBox.addItem("Maryland");
        stateJComboBox.addItem("Massachusetts");
        stateJComboBox.addItem("New York");
    }

    public void populateEnterpriseTypeComboBox() {
        enterpriseTypeJComboBox.removeAllItems();

        for (Enterprise.TypeOfEnterprise type : Enterprise.TypeOfEnterprise.values()) {
            if (type == Enterprise.TypeOfEnterprise.VaccineManufacturer
                    || type == Enterprise.TypeOfEnterprise.PHD) {
                enterpriseTypeJComboBox.addItem(type);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backJButton1 = new javax.swing.JButton();
        displayJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        phdJInternalFrame = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        enterpriseJLabel = new javax.swing.JLabel();
        enterpriseNameJLabel = new javax.swing.JLabel();
        stateNameJLabel = new javax.swing.JLabel();
        stateJComboBox = new javax.swing.JComboBox();
        enterpriseNameJTextField = new javax.swing.JTextField();
        enterpriseTypeJComboBox = new javax.swing.JComboBox();
        addEnterpriseJButton = new javax.swing.JButton();
        removeJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Add State/Regional level Enterprises");

        backJButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        backJButton1.setText("<< Back");
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });

        displayJLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        displayJLabel.setText("Display of Enterprises added");

        enterpriseJTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise Type", "Enterprise Name", "State Name"
            }
        ));
        enterpriseJTable.setRowHeight(25);
        jScrollPane1.setViewportView(enterpriseJTable);

        phdJInternalFrame.setVisible(true);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Choose Enterprise");

        enterpriseJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        enterpriseJLabel.setText("Enterprise Type");

        enterpriseNameJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        enterpriseNameJLabel.setText("Enterprise Name");

        stateNameJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        stateNameJLabel.setText("State Name");

        stateJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        enterpriseTypeJComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        enterpriseTypeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        enterpriseTypeJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseTypeJComboBoxActionPerformed(evt);
            }
        });

        addEnterpriseJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addEnterpriseJButton.setText("Add Enterprise");
        addEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEnterpriseJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout phdJInternalFrameLayout = new javax.swing.GroupLayout(phdJInternalFrame.getContentPane());
        phdJInternalFrame.getContentPane().setLayout(phdJInternalFrameLayout);
        phdJInternalFrameLayout.setHorizontalGroup(
            phdJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phdJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(phdJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(phdJInternalFrameLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(phdJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addEnterpriseJButton)
                            .addGroup(phdJInternalFrameLayout.createSequentialGroup()
                                .addGroup(phdJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enterpriseNameJLabel)
                                    .addComponent(enterpriseJLabel)
                                    .addComponent(stateNameJLabel))
                                .addGap(18, 18, 18)
                                .addGroup(phdJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(enterpriseTypeJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(enterpriseNameJTextField)
                                    .addComponent(stateJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        phdJInternalFrameLayout.setVerticalGroup(
            phdJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phdJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addGroup(phdJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseJLabel)
                    .addComponent(enterpriseTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(phdJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseNameJLabel)
                    .addComponent(enterpriseNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(phdJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateNameJLabel)
                    .addComponent(stateJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addEnterpriseJButton)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        removeJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        removeJButton.setText("Remove Enterprise");
        removeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phdJInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(displayJLabel))
                        .addGap(0, 178, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeJButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(phdJInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(displayJLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton1)
                    .addComponent(removeJButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enterpriseTypeJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseTypeJComboBoxActionPerformed
        // TODO add your handling code here:
        Enterprise.TypeOfEnterprise type = (Enterprise.TypeOfEnterprise) enterpriseTypeJComboBox.getSelectedItem();

        if (type == Enterprise.TypeOfEnterprise.PHD) {
            stateJComboBox.setEnabled(true);
        } else {
            stateJComboBox.setSelectedIndex(0);
            stateJComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_enterpriseTypeJComboBoxActionPerformed

    private void addEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEnterpriseJButtonActionPerformed
        // TODO add your handling code here:
        Enterprise.TypeOfEnterprise type = (Enterprise.TypeOfEnterprise) enterpriseTypeJComboBox.getSelectedItem();
        String enterpriseName = enterpriseNameJTextField.getText();
        String stateName = String.valueOf(stateJComboBox.getSelectedItem());

        if (enterpriseName.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter the name!");
            return;
        }

        if (type == null) {
            JOptionPane.showMessageDialog(null, "Select enterprise type!");
            return;
        }

        if (stateJComboBox.isEnabled() == true && stateName.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter state name!");
            return;
        }

        Enterprise e = null;

        //If PHD is being added
        if (!stateName.trim().equals("")) {
            e = network.getEnterpriseDirectory().addAndCreateEnterprise(type, enterpriseName, network, stateName);
            if (e == null) {
                JOptionPane.showMessageDialog(null, "Enterprise already exists, you cannot add same enterprise!");
                return;
            }
            enterprise.getPhdList().add((PHDEnterprise) e);
            //If Manufacturer is being added            
        } else {
            e = network.getEnterpriseDirectory().addAndCreateEnterprise(type, enterpriseName, network);
            if (e == null) {
                JOptionPane.showMessageDialog(null, "Enterprise already exists, you cannot add same enterprise!");
                return;
            }
            enterprise.getVaccineManufacturerList().add((VaccineManufacturerEnterprise) e);
        }
        populateEnterpriseTable();
        enterpriseNameJTextField.setText("");
        stateJComboBox.setSelectedIndex(0);
        JOptionPane.showMessageDialog(null, "Enterprise added!");
    }//GEN-LAST:event_addEnterpriseJButtonActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = enterpriseJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Kindly select an enterprise!");
            return;
        }
        Enterprise choseEnterprise = (Enterprise) enterpriseJTable.getValueAt(selectedRow, 1);
        Enterprise.TypeOfEnterprise type = (Enterprise.TypeOfEnterprise) enterpriseJTable.getValueAt(selectedRow, 0);

        network.getEnterpriseDirectory().removeEnterpriseObject(choseEnterprise);
        if(type.getValue().equals(Enterprise.TypeOfEnterprise.PHD.getValue())){
        enterprise.getPhdList().remove(choseEnterprise);
        } else if(type.getValue().equals(Enterprise.TypeOfEnterprise.VaccineManufacturer.getValue())){
        enterprise.getVaccineManufacturerList().remove(choseEnterprise);
        }
        populateEnterpriseTable();
    }//GEN-LAST:event_removeJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEnterpriseJButton;
    private javax.swing.JButton backJButton1;
    private javax.swing.JLabel displayJLabel;
    private javax.swing.JLabel enterpriseJLabel;
    private javax.swing.JTable enterpriseJTable;
    private javax.swing.JLabel enterpriseNameJLabel;
    private javax.swing.JTextField enterpriseNameJTextField;
    private javax.swing.JComboBox enterpriseTypeJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JInternalFrame phdJInternalFrame;
    private javax.swing.JButton removeJButton;
    private javax.swing.JComboBox stateJComboBox;
    private javax.swing.JLabel stateNameJLabel;
    // End of variables declaration//GEN-END:variables
}
