/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CentreForDiseaseControl;

import UserInterface.Sites.ViewBills;
import Business.Enterprise.CDCEnterprise;
import Business.Enterprise.NationalDistributorEnterprise;
import Business.Organization.CDC.CDCOperationsOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Rishika Idnani
 */
public class CDCOperationsWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form CDCOperationsWorkArea
     */
    private JPanel userProcessContainer;
    private CDCEnterprise enterprise;
    private CDCOperationsOrganization organization;
    private UserAccount userAccount;

    public CDCOperationsWorkArea(JPanel userProcessContainer, CDCEnterprise enterprise, CDCOperationsOrganization organization, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDescriptionJLabel = new javax.swing.JLabel();
        viewOrdersJButton = new javax.swing.JButton();
        viewFeedbackJButton = new javax.swing.JButton();
        viewBillsJButton = new javax.swing.JButton();

        panelDescriptionJLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelDescriptionJLabel.setText("Centre for Disease Control - Operations");

        viewOrdersJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        viewOrdersJButton.setText("View Orders from States >>");
        viewOrdersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrdersJButtonActionPerformed(evt);
            }
        });

        viewFeedbackJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        viewFeedbackJButton.setText("View feedback from Providers >>");
        viewFeedbackJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFeedbackJButtonActionPerformed(evt);
            }
        });

        viewBillsJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        viewBillsJButton.setText("View Bills >>");
        viewBillsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBillsJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDescriptionJLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(viewBillsJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewFeedbackJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewOrdersJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)))
                .addContainerGap(336, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDescriptionJLabel)
                .addGap(27, 27, 27)
                .addComponent(viewOrdersJButton)
                .addGap(28, 28, 28)
                .addComponent(viewFeedbackJButton)
                .addGap(28, 28, 28)
                .addComponent(viewBillsJButton)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewOrdersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrdersJButtonActionPerformed
        // TODO add your handling code here:
        ViewVaccineOrders panel = new ViewVaccineOrders(userProcessContainer, enterprise, organization, userAccount);

        userProcessContainer.add("ViewVaccineOrders", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewOrdersJButtonActionPerformed

    private void viewFeedbackJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFeedbackJButtonActionPerformed
        // TODO add your handling code here:
        ViewFeedbackFromProviders panel = new ViewFeedbackFromProviders(userProcessContainer, enterprise, organization, userAccount);

        userProcessContainer.add("ViewFeedback", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewFeedbackJButtonActionPerformed

    private void viewBillsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBillsJButtonActionPerformed
        // TODO add your handling code here:
        ViewPatientBills panel = new ViewPatientBills(userProcessContainer, enterprise, organization, userAccount);

        userProcessContainer.add("ViewBills", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewBillsJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel panelDescriptionJLabel;
    private javax.swing.JButton viewBillsJButton;
    private javax.swing.JButton viewFeedbackJButton;
    private javax.swing.JButton viewOrdersJButton;
    // End of variables declaration//GEN-END:variables
}
