/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CentreForDiseaseControl;

import Business.Enterprise.CDCEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PHDEnterprise;
import Business.Enterprise.VaccineManufacturerEnterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rishika Idnani
 */
public class CDCWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form CDCWorkArea
     */
    private JPanel userProcessContainer;
    private CDCEnterprise enterprise;
    private Network network;

    public CDCWorkArea(JPanel userProcessContainer, CDCEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.network = enterprise.getNetwork();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDescriptionJLabel = new javax.swing.JLabel();
        manageEnterpriseJButton = new javax.swing.JButton();
        addDiseaseJButton = new javax.swing.JButton();
        addPhdsJButton = new javax.swing.JButton();
        manageOrganizationJButton = new javax.swing.JButton();
        dataAnalysisJButton = new javax.swing.JButton();

        panelDescriptionJLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelDescriptionJLabel.setText("Centre for Disease Control");

        manageEnterpriseJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        manageEnterpriseJButton.setText("Manage Enterprise/Organization Account >>");
        manageEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseJButtonActionPerformed(evt);
            }
        });

        addDiseaseJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addDiseaseJButton.setText("Disease Details >>");
        addDiseaseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDiseaseJButtonActionPerformed(evt);
            }
        });

        addPhdsJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addPhdsJButton.setText("Add PHDs and Vaccine Manufacturers >>");
        addPhdsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPhdsJButtonActionPerformed(evt);
            }
        });

        manageOrganizationJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        manageOrganizationJButton.setText("Manage Organizations >>");
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });

        dataAnalysisJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dataAnalysisJButton.setText("Data Analysis >>");
        dataAnalysisJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataAnalysisJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(panelDescriptionJLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageOrganizationJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                            .addComponent(addPhdsJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                            .addComponent(manageEnterpriseJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                            .addComponent(addDiseaseJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                            .addComponent(dataAnalysisJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDescriptionJLabel)
                .addGap(32, 32, 32)
                .addComponent(addPhdsJButton)
                .addGap(18, 18, 18)
                .addComponent(manageOrganizationJButton)
                .addGap(18, 18, 18)
                .addComponent(manageEnterpriseJButton)
                .addGap(18, 18, 18)
                .addComponent(addDiseaseJButton)
                .addGap(18, 18, 18)
                .addComponent(dataAnalysisJButton)
                .addContainerGap(101, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseJButtonActionPerformed
        // TODO add your handling code here:
        ManageUserAccount panel = new ManageUserAccount(userProcessContainer, enterprise);

        userProcessContainer.add("ManageEnterprises", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseJButtonActionPerformed

    private void addDiseaseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDiseaseJButtonActionPerformed
        // TODO add your handling code here:
        AddDiseaseJPanel panel = new AddDiseaseJPanel(userProcessContainer, enterprise);

        userProcessContainer.add("AddDisease", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addDiseaseJButtonActionPerformed

    private void addPhdsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPhdsJButtonActionPerformed
        // TODO add your handling code here:
        AddPhdAndManufacturer panel = new AddPhdAndManufacturer(userProcessContainer, enterprise);

        userProcessContainer.add("ViewVaccineOrders", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addPhdsJButtonActionPerformed

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed
        // TODO add your handling code here:
        ManageCDCOrganization panel = new ManageCDCOrganization(userProcessContainer, enterprise);

        userProcessContainer.add("ManageOrganization", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void dataAnalysisJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataAnalysisJButtonActionPerformed
        // TODO add your handling code here:
        DataAnalysis panel = new DataAnalysis(userProcessContainer, enterprise);

        userProcessContainer.add("DataAnalysis", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_dataAnalysisJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDiseaseJButton;
    private javax.swing.JButton addPhdsJButton;
    private javax.swing.JButton dataAnalysisJButton;
    private javax.swing.JButton manageEnterpriseJButton;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JLabel panelDescriptionJLabel;
    // End of variables declaration//GEN-END:variables
}
