/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CentreForDiseaseControl;

import Business.Enterprise.CDCEnterprise;
import Business.Enterprise.NationalDistributorEnterprise;
import Business.Enterprise.PHDEnterprise;
import Business.Enterprise.SiteEnterprise;
import Business.Organization.CDC.CDCOperationsOrganization;
import Business.Organization.Organization;
import Business.Organization.Sites.ProviderOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.BillTheCdc;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rishika Idnani
 */
public class ViewPatientBills extends javax.swing.JPanel {

    /**
     * Creates new form ViewPatientBills
     */
    private JPanel userProcessContainer;
    private CDCEnterprise enterprise;
    private CDCOperationsOrganization organization;
    private UserAccount userAccount;

    public ViewPatientBills(JPanel userProcessContainer, CDCEnterprise enterprise, CDCOperationsOrganization organization, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = userAccount;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) billJTable.getModel();
        model.setRowCount(0);
        
        for (PHDEnterprise e : enterprise.getPhdList()) {
            for (SiteEnterprise sE : e.getSiteList()) {
                for (Organization o : sE.getOrganizationDirectory().getOrganizationList()) {
                    if (o instanceof ProviderOrganization) {
                        ProviderOrganization providerOrganization = (ProviderOrganization) o;
                        for (WorkRequest w : providerOrganization.getWorkQueue().getWorkRequestList()) {
                            if (w instanceof BillTheCdc) {
                                BillTheCdc wr = (BillTheCdc) w;
                                Object row[] = new Object[5];
                                row[0] = wr.getPatient();
                                row[1] = wr.getVaccine();
                                row[2] = wr.getVaccine().getDisease();
                                row[3] = wr.getAmount();
                                row[4] = wr.getPatient().getInsuranceInformation();
                                model.addRow(row);
                            }
                        }
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDesciptionJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        billJTable = new javax.swing.JTable();
        pendingJLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        panelDesciptionJLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelDesciptionJLabel.setText("View Bills");

        billJTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        billJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Vaccine", "Disease", "Amount", "Insurance Status"
            }
        ));
        billJTable.setRowHeight(25);
        jScrollPane1.setViewportView(billJTable);

        pendingJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pendingJLabel.setText("Pending Bills");

        backJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelDesciptionJLabel)
                            .addComponent(pendingJLabel)
                            .addComponent(backJButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDesciptionJLabel)
                .addGap(31, 31, 31)
                .addComponent(pendingJLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(backJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTable billJTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel panelDesciptionJLabel;
    private javax.swing.JLabel pendingJLabel;
    // End of variables declaration//GEN-END:variables
}
