/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PublicHealthDepartment;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PHDEnterprise;
import Business.Enterprise.SiteEnterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rishika Idnani
 */
public class ManageSites extends javax.swing.JPanel {

    /**
     * Creates new form ManageSites
     */
    private JPanel userProcessContainer;
    private PHDEnterprise enterprise;
    private String stateName;
    private Network network;

    public ManageSites(JPanel userProcessContainer, PHDEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.stateName = enterprise.getStateName();
        this.network = enterprise.getNetwork();
        structureInternalFrame();
        populateEnterpriseTypeComboBox();
        populateEnterpriseTable();
        populatePinComboBox();
    }

    public void populatePinComboBox() {
        pinJComboBox.removeAllItems();

        if (stateName.equals("California")) {
            pinJComboBox.addItem("90210");
        } else if (stateName.equals("Florida")) {
            pinJComboBox.addItem("32207");
        } else if (stateName.equals("Illinois")) {
            pinJComboBox.addItem("60004");
        } else if (stateName.equals("Maryland")) {
            pinJComboBox.addItem("21740");
        } else if (stateName.equals("Massachusetts")) {
            pinJComboBox.addItem("02120");
            pinJComboBox.addItem("02123");
        } else if (stateName.equals("New York")) {
            pinJComboBox.addItem("10001");
        }
    }

    public void structureInternalFrame() {
        javax.swing.plaf.InternalFrameUI siteFrameUI = siteJInternalFrame.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) siteFrameUI).setNorthPane(null);
    }

    public void populateEnterpriseTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseJTable.getModel();
        model.setRowCount(0);

        for (SiteEnterprise enterprise : enterprise.getSiteList()) {
            Object row[] = new Object[4];
            row[0] = enterprise.getTypeOfSite();
            row[1] = enterprise;
            row[2] = enterprise.getStateName();
            row[3] = enterprise.getPinCode();
            model.addRow(row);
        }
    }

    public void populateEnterpriseTypeComboBox() {
        siteTypeJComboBox.removeAllItems();

        siteTypeJComboBox.addItem("Hospital");
        siteTypeJComboBox.addItem("Pharmacy");
        siteTypeJComboBox.addItem("Clinic");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        displayJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        siteJInternalFrame = new javax.swing.JInternalFrame();
        enterpriseNameJTextField = new javax.swing.JTextField();
        siteTypeJComboBox = new javax.swing.JComboBox();
        enterpriseNameJLabel = new javax.swing.JLabel();
        enterpriseJLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addEnterpriseJButton = new javax.swing.JButton();
        pinJLabel = new javax.swing.JLabel();
        pinJComboBox = new javax.swing.JComboBox();
        removeJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Manage Sites");

        backJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        displayJLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        displayJLabel.setText("Display of Enterprises added");

        enterpriseJTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Site Type", "Site Name", "State Name", "Pin Code"
            }
        ));
        enterpriseJTable.setRowHeight(23);
        jScrollPane1.setViewportView(enterpriseJTable);

        siteJInternalFrame.setVisible(true);

        siteTypeJComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        siteTypeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        siteTypeJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siteTypeJComboBoxActionPerformed(evt);
            }
        });

        enterpriseNameJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        enterpriseNameJLabel.setText("Site Name");

        enterpriseJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        enterpriseJLabel.setText("Site Type");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Register the sites");

        addEnterpriseJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addEnterpriseJButton.setText("Add Enterprise");
        addEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEnterpriseJButtonActionPerformed(evt);
            }
        });

        pinJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pinJLabel.setText("Pin Code");

        pinJComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pinJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout siteJInternalFrameLayout = new javax.swing.GroupLayout(siteJInternalFrame.getContentPane());
        siteJInternalFrame.getContentPane().setLayout(siteJInternalFrameLayout);
        siteJInternalFrameLayout.setHorizontalGroup(
            siteJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siteJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(siteJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(siteJInternalFrameLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(siteJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterpriseNameJLabel)
                            .addComponent(enterpriseJLabel)
                            .addComponent(pinJLabel))
                        .addGap(18, 18, 18)
                        .addGroup(siteJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(siteTypeJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(enterpriseNameJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(pinJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addComponent(addEnterpriseJButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        siteJInternalFrameLayout.setVerticalGroup(
            siteJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siteJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(siteJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(siteJInternalFrameLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(siteJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enterpriseJLabel)
                            .addComponent(siteTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(siteJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enterpriseNameJLabel)
                            .addComponent(enterpriseNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(siteJInternalFrameLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(addEnterpriseJButton)))
                .addGap(18, 18, 18)
                .addGroup(siteJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinJLabel)
                    .addComponent(pinJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        removeJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        removeJButton.setText("Remove Sites");
        removeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(siteJInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(displayJLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(backJButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeJButton))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(siteJInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(displayJLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(removeJButton))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void siteTypeJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siteTypeJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_siteTypeJComboBoxActionPerformed

    private void addEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEnterpriseJButtonActionPerformed
        // TODO add your handling code here:
        int pinCode = Integer.parseInt(String.valueOf(pinJComboBox.getSelectedItem()));
        String siteType = String.valueOf(siteTypeJComboBox.getSelectedItem());
        String siteName = enterpriseNameJTextField.getText();

        if (siteName.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter the name!");
            return;
        }

        if (siteType.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Select site type!");
            return;
        }

        Enterprise e = null;
        e = network.getEnterpriseDirectory().addAndCreateSiteEnterprise(siteType, siteName, stateName, pinCode);
        if (e == null) {
            JOptionPane.showMessageDialog(null, "Enterprise not added!!");
            return;
        }
        enterprise.getSiteList().add((SiteEnterprise) e);
        enterpriseNameJTextField.setText("");
        populateEnterpriseTable();
    }//GEN-LAST:event_addEnterpriseJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = enterpriseJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Kindly select a row");
            return;
        }

        SiteEnterprise siteEnterprise = (SiteEnterprise) enterpriseJTable.getValueAt(selectedRow, 1);
        network.getEnterpriseDirectory().removeEnterpriseObject(siteEnterprise);
        enterprise.getSiteList().remove(siteEnterprise);
        populateEnterpriseTable();
    }//GEN-LAST:event_removeJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEnterpriseJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel displayJLabel;
    private javax.swing.JLabel enterpriseJLabel;
    private javax.swing.JTable enterpriseJTable;
    private javax.swing.JLabel enterpriseNameJLabel;
    private javax.swing.JTextField enterpriseNameJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox pinJComboBox;
    private javax.swing.JLabel pinJLabel;
    private javax.swing.JButton removeJButton;
    private javax.swing.JInternalFrame siteJInternalFrame;
    private javax.swing.JComboBox siteTypeJComboBox;
    // End of variables declaration//GEN-END:variables
}
