/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PublicHealthDepartment;

import Business.Enterprise.PHDEnterprise;
import Business.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rishika Idnani
 */
public class ManagePhdOrganizations extends javax.swing.JPanel {

    /**
     * Creates new form ManagePhdOrganizations
     */
    private JPanel userProcessContainer;
    private PHDEnterprise enterprise;

    public ManagePhdOrganizations(JPanel userProcessContainer, PHDEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        structureInternalFrame();
        populateTable();
        populateOrganizationComboBox();
    }

    public void structureInternalFrame() {
        javax.swing.plaf.InternalFrameUI orgFrameUI = orgJInternalFrame.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) orgFrameUI).setNorthPane(null);
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) organizationJTable.getModel();
        model.setRowCount(0);

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            Object row[] = new Object[2];
            row[0] = organization;
            row[1] = organization.getType();
            model.addRow(row);
        }
    }

    public void populateOrganizationComboBox() {
        organizationTypeJComboBox.removeAllItems();
        for (Organization.TypeOfOrganization type : Organization.TypeOfOrganization.values()) {
            if (type == Organization.TypeOfOrganization.PhdOperations) {
                organizationTypeJComboBox.addItem(type);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJLabel = new javax.swing.JLabel();
        backJButton1 = new javax.swing.JButton();
        displayJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        organizationJTable = new javax.swing.JTable();
        orgJInternalFrame = new javax.swing.JInternalFrame();
        addOrganizationJLabel = new javax.swing.JLabel();
        organizationTypeJLabel = new javax.swing.JLabel();
        organizationNameJLabel = new javax.swing.JLabel();
        organizationNameJTextField = new javax.swing.JTextField();
        organizationTypeJComboBox = new javax.swing.JComboBox();
        addOrganizationJButton = new javax.swing.JButton();
        removeJButton = new javax.swing.JButton();

        panelJLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelJLabel.setText("Manage Organizations");

        backJButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        backJButton1.setText("<< Back");
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });

        displayJLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        displayJLabel.setText("Display of Organizations added");

        organizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Organization Name", "Organization Type"
            }
        ));
        organizationJTable.setRowHeight(25);
        jScrollPane1.setViewportView(organizationJTable);

        orgJInternalFrame.setVisible(true);

        addOrganizationJLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        addOrganizationJLabel.setText("Add Organization");

        organizationTypeJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        organizationTypeJLabel.setText("Organization Type");

        organizationNameJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        organizationNameJLabel.setText("Organization Name");

        organizationNameJTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        organizationTypeJComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        organizationTypeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addOrganizationJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addOrganizationJButton.setText("Add Organization");
        addOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrganizationJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout orgJInternalFrameLayout = new javax.swing.GroupLayout(orgJInternalFrame.getContentPane());
        orgJInternalFrame.getContentPane().setLayout(orgJInternalFrameLayout);
        orgJInternalFrameLayout.setHorizontalGroup(
            orgJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orgJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(orgJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orgJInternalFrameLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(orgJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(organizationTypeJLabel)
                            .addComponent(organizationNameJLabel))
                        .addGap(28, 28, 28)
                        .addGroup(orgJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(organizationTypeJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(organizationNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(addOrganizationJButton))
                    .addComponent(addOrganizationJLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        orgJInternalFrameLayout.setVerticalGroup(
            orgJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orgJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addOrganizationJLabel)
                .addGroup(orgJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orgJInternalFrameLayout.createSequentialGroup()
                        .addGroup(orgJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(organizationTypeJLabel)
                            .addComponent(organizationTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(orgJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(organizationNameJLabel)
                            .addComponent(organizationNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(orgJInternalFrameLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(addOrganizationJButton)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        removeJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        removeJButton.setText("Remove Organization");
        removeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backJButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeJButton))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(displayJLabel)
                                .addComponent(panelJLabel)
                                .addComponent(orgJInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelJLabel)
                .addGap(29, 29, 29)
                .addComponent(orgJInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(displayJLabel)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton1)
                    .addComponent(removeJButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrganizationJButtonActionPerformed
        // TODO add your handling code here:
        String organizationName = organizationNameJTextField.getText();

        if (organizationName.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Kindly input organization name");
            return;
        }

        Organization.TypeOfOrganization type = (Organization.TypeOfOrganization) organizationTypeJComboBox.getSelectedItem();

        Organization o = enterprise.getOrganizationDirectory().addOrganization(type, organizationName);
        if (o == null) {
            JOptionPane.showMessageDialog(null, "Organization already exists!");
            return;
        }
        organizationNameJTextField.setText("");
        populateTable();
    }//GEN-LAST:event_addOrganizationJButtonActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = organizationJTable.getSelectedRow();
        
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Kindly select a row");
            return;
        }
        
        Organization organization = (Organization)organizationJTable.getValueAt(selectedRow, 0);
        
        enterprise.getOrganizationDirectory().removeOrganization(organization);
        populateTable();
    }//GEN-LAST:event_removeJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOrganizationJButton;
    private javax.swing.JLabel addOrganizationJLabel;
    private javax.swing.JButton backJButton1;
    private javax.swing.JLabel displayJLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JInternalFrame orgJInternalFrame;
    private javax.swing.JTable organizationJTable;
    private javax.swing.JLabel organizationNameJLabel;
    private javax.swing.JTextField organizationNameJTextField;
    private javax.swing.JComboBox organizationTypeJComboBox;
    private javax.swing.JLabel organizationTypeJLabel;
    private javax.swing.JLabel panelJLabel;
    private javax.swing.JButton removeJButton;
    // End of variables declaration//GEN-END:variables
}
