/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PublicHealthDepartment;

import Business.Enterprise.CDCEnterprise;
import Business.Enterprise.PHDEnterprise;
import Business.Enterprise.SiteEnterprise;
import Business.Enterprise.VaccineManufacturerEnterprise;
import Business.Order.OrderItem;
import Business.Organization.Organization;
import Business.Organization.PHD.PhdOperationsOrganization;
import Business.Organization.Sites.SiteOperationOrganization;
import Business.UserAccount.UserAccount;
import Business.Vaccine.Vaccine;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rishika Idnani
 */
public class OverviewOfDosages extends javax.swing.JPanel {

    /**
     * Creates new form OverviewOfDosages
     */
    private JPanel userProcessContainer;
    private PHDEnterprise enterprise;
    private PhdOperationsOrganization organization;
    private UserAccount userAccount;
    private CDCEnterprise cdcEnterprise;

    public OverviewOfDosages(JPanel userProcessContainer, PHDEnterprise enterprise, PhdOperationsOrganization organization, UserAccount userAccount, CDCEnterprise cdcEnterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = userAccount;
        this.cdcEnterprise = cdcEnterprise;
        populateVaccine();
    }

    public void populateVaccine() {
        vaccineJComboBox.removeAllItems();

        for (VaccineManufacturerEnterprise vmEnterprise : cdcEnterprise.getVaccineManufacturerList()) {
            for (Vaccine vaccine : vmEnterprise.getVaccineCatalog().getVaccineList()) {
                vaccineJComboBox.addItem(vaccine);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDescriptionJLabel = new javax.swing.JLabel();
        chooseJLabel = new javax.swing.JLabel();
        vaccineJComboBox = new javax.swing.JComboBox();
        displayJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doseJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();

        panelDescriptionJLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelDescriptionJLabel.setText("Overview of Dosages");

        chooseJLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        chooseJLabel.setText("Choose the vaccine: ");

        vaccineJComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        vaccineJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        vaccineJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccineJComboBoxActionPerformed(evt);
            }
        });

        displayJLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        displayJLabel.setText("Display of dose available at various sites");

        doseJTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        doseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Site", "Quantity", "Disease", "Available to Provider"
            }
        ));
        doseJTable.setRowHeight(25);
        jScrollPane1.setViewportView(doseJTable);

        backJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelDescriptionJLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chooseJLabel)
                                .addGap(18, 18, 18)
                                .addComponent(vaccineJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(displayJLabel)
                            .addComponent(backJButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDescriptionJLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseJLabel)
                    .addComponent(vaccineJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(displayJLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(backJButton)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void vaccineJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccineJComboBoxActionPerformed
        // TODO add your handling code here:
        Vaccine vaccine = (Vaccine) vaccineJComboBox.getSelectedItem();

        DefaultTableModel model = (DefaultTableModel) doseJTable.getModel();
        model.setRowCount(0);

        for (SiteEnterprise en : enterprise.getSiteList()) {
            for (Organization o : en.getOrganizationDirectory().getOrganizationList()) {
                if (o instanceof SiteOperationOrganization) {
                    SiteOperationOrganization organization = (SiteOperationOrganization) o;

                    for (OrderItem oi : organization.getVaccineInventory()) {
                        if (oi.getVaccine() == vaccine && oi.getTotalQuantity() > 0 && oi.getExpiryDate().after(new Date())) {
                            Object row[] = new Object[4];
                            row[0] = en;
                            row[1] = oi.getTotalQuantity();
                            row[2] = oi.getVaccine().getDisease();
                            row[3] = oi.getProvider();
                            model.addRow(row);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_vaccineJComboBoxActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel chooseJLabel;
    private javax.swing.JLabel displayJLabel;
    private javax.swing.JTable doseJTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel panelDescriptionJLabel;
    private javax.swing.JComboBox vaccineJComboBox;
    // End of variables declaration//GEN-END:variables
}
