/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdministration;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import java.awt.CardLayout;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.ArrayList;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Rishika Idnani
 */
public class SystemAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkArea
     */
    private JPanel userProcessContainer;
    private Ecosystem system;
    private DefaultMutableTreeNode networkNode;

    public SystemAdminWorkArea(JPanel userProcessContainer, Ecosystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;

        Font font = panelDescriptionJLabel.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        panelDescriptionJLabel.setFont(font.deriveFont(attributes));

        structureInternalFrame();
        populateJTree();
        populateEnterpriseComboBox();

        populateCountry();
    }

    public void structureInternalFrame() {
        javax.swing.plaf.InternalFrameUI networkFrameUI = networkJInternalFrame.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) networkFrameUI).setNorthPane(null);

        javax.swing.plaf.InternalFrameUI enterpriseFrameUI = enterpriseJInternalFrame.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) enterpriseFrameUI).setNorthPane(null);
    }

    public void populateCountry() {
        countryListJComboBox.removeAllItems();
        String locales[] = Locale.getISOCountries();

        for (String country : locales) {
            countryListJComboBox.addItem(new Locale("", country).getDisplayCountry());
        }
    }

    public void populateJTree() {
        ArrayList<Network> networkList = system.getNetworkDirectory().getNetworkList();
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Organization> organizationList;
        Network network;
        Enterprise enterprise;
        Organization organization;

        DefaultTreeModel model = (DefaultTreeModel) jTree.getModel();

        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        networkNode = new DefaultMutableTreeNode("Networks");
        root.insert(networkNode, 0);

        DefaultMutableTreeNode networkNodes;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;
        for (int i = 0; i < networkList.size(); i++) {
            network = networkList.get(i);
            networkNodes = new DefaultMutableTreeNode(network.getName());
            networkNode.insert(networkNodes, i);

            enterpriseList = network.getEnterpriseDirectory().getEnterpriseList();

            for (int j = 0; j < enterpriseList.size(); j++) {
                enterprise = enterpriseList.get(j);
                enterpriseNode = new DefaultMutableTreeNode(enterprise.getName());
                networkNodes.insert(enterpriseNode, j);

                organizationList = enterprise.getOrganizationDirectory().getOrganizationList();
                for (int k = 0; k < organizationList.size(); k++) {
                    organization = organizationList.get(k);
                    organizationNode = new DefaultMutableTreeNode(organization.getName());
                    enterpriseNode.insert(organizationNode, k);
                }
            }
        }

        model.reload();
    }

    public void populateEnterpriseComboBox() {
        enterpriseJComboBox.removeAllItems();

        for (Enterprise.TypeOfEnterprise type : Enterprise.TypeOfEnterprise.values()) {
            if (type == Enterprise.TypeOfEnterprise.CDC
                    || type == Enterprise.TypeOfEnterprise.NationalDistributor) {
                enterpriseJComboBox.addItem(type);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        panelDescriptionJLabel = new javax.swing.JLabel();
        manageEnterpriseAdminJButton = new javax.swing.JButton();
        networkJInternalFrame = new javax.swing.JInternalFrame();
        instructionJLabel = new javax.swing.JLabel();
        networkNameJLabel = new javax.swing.JLabel();
        countryListJComboBox = new javax.swing.JComboBox();
        removeNetworkJButton = new javax.swing.JButton();
        addNetworkJButton = new javax.swing.JButton();
        enterpriseJInternalFrame = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        enterpriseTypeJLabel = new javax.swing.JLabel();
        enterpriseNameJLabel = new javax.swing.JLabel();
        enterpriseNameJTextField = new javax.swing.JTextField();
        enterpriseJComboBox = new javax.swing.JComboBox();
        addEnterpriseJButton = new javax.swing.JButton();
        removeEnterpriseJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jTree.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("System");
        jTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree);

        panelDescriptionJLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelDescriptionJLabel.setText("System Administration Work Area");

        manageEnterpriseAdminJButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        manageEnterpriseAdminJButton.setText("Manage Enterprise Admin >>");
        manageEnterpriseAdminJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEnterpriseAdminJButtonActionPerformed(evt);
            }
        });

        networkJInternalFrame.setVisible(true);

        instructionJLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        instructionJLabel.setText("Enter the name of Network");

        networkNameJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        networkNameJLabel.setText("Network Name");

        countryListJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        removeNetworkJButton.setText("<<");
        removeNetworkJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeNetworkJButtonActionPerformed(evt);
            }
        });

        addNetworkJButton.setText(">>");
        addNetworkJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNetworkJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout networkJInternalFrameLayout = new javax.swing.GroupLayout(networkJInternalFrame.getContentPane());
        networkJInternalFrame.getContentPane().setLayout(networkJInternalFrameLayout);
        networkJInternalFrameLayout.setHorizontalGroup(
            networkJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(networkJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(networkJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(networkJInternalFrameLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(networkNameJLabel)
                        .addGap(35, 35, 35)
                        .addComponent(countryListJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29)
                        .addGroup(networkJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addNetworkJButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(removeNetworkJButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(instructionJLabel))
                .addGap(64, 64, 64))
        );
        networkJInternalFrameLayout.setVerticalGroup(
            networkJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(networkJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(networkJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(networkJInternalFrameLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(addNetworkJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeNetworkJButton))
                    .addGroup(networkJInternalFrameLayout.createSequentialGroup()
                        .addComponent(instructionJLabel)
                        .addGap(26, 26, 26)
                        .addGroup(networkJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(networkNameJLabel)
                            .addComponent(countryListJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        enterpriseJInternalFrame.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Enter the name of the Enterprise");

        enterpriseTypeJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        enterpriseTypeJLabel.setText("Enterprise Type");

        enterpriseNameJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        enterpriseNameJLabel.setText("Enterprise Name");

        enterpriseNameJTextField.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        enterpriseJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addEnterpriseJButton.setText(">>");
        addEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEnterpriseJButtonActionPerformed(evt);
            }
        });

        removeEnterpriseJButton.setText("<<");
        removeEnterpriseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEnterpriseJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout enterpriseJInternalFrameLayout = new javax.swing.GroupLayout(enterpriseJInternalFrame.getContentPane());
        enterpriseJInternalFrame.getContentPane().setLayout(enterpriseJInternalFrameLayout);
        enterpriseJInternalFrameLayout.setHorizontalGroup(
            enterpriseJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterpriseJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enterpriseJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(enterpriseJInternalFrameLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(enterpriseJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterpriseTypeJLabel)
                            .addComponent(enterpriseNameJLabel))
                        .addGap(18, 18, 18)
                        .addGroup(enterpriseJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(enterpriseJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(enterpriseNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(enterpriseJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addEnterpriseJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeEnterpriseJButton)))
                    .addComponent(jLabel1))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        enterpriseJInternalFrameLayout.setVerticalGroup(
            enterpriseJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterpriseJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(enterpriseJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseTypeJLabel)
                    .addComponent(enterpriseJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addEnterpriseJButton))
                .addGap(18, 18, 18)
                .addGroup(enterpriseJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseNameJLabel)
                    .addComponent(enterpriseNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeEnterpriseJButton))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("System Hierarchy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(networkJInternalFrame)
                            .addComponent(enterpriseJInternalFrame)
                            .addComponent(manageEnterpriseAdminJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelDescriptionJLabel))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDescriptionJLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(networkJInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(enterpriseJInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(manageEnterpriseAdminJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addNetworkJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNetworkJButtonActionPerformed
        DefaultTreeModel model = (DefaultTreeModel) jTree.getModel();

        String networkName = String.valueOf(countryListJComboBox.getSelectedItem());
        //String networkName = networkNameJTextField.getText();
        if (networkName.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter network to be added");
            return;
        }

        if (networkNode != null) {
            Network network = system.getNetworkDirectory().addAndCreateNetwork(networkName);
            if (network == null) {
                JOptionPane.showMessageDialog(null, "Network with the name already exists!");
                return;
            }
            DefaultMutableTreeNode newNetwork = new DefaultMutableTreeNode(networkName);
            networkNode.insert(newNetwork, 0);
            countryListJComboBox.setSelectedIndex(0);
            JOptionPane.showMessageDialog(null, "Network added!");
        }
        model.reload();
    }//GEN-LAST:event_addNetworkJButtonActionPerformed

    private void addEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEnterpriseJButtonActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel model = (DefaultTreeModel) jTree.getModel();

        Enterprise.TypeOfEnterprise type = (Enterprise.TypeOfEnterprise) enterpriseJComboBox.getSelectedItem();
        String enterpriseName = enterpriseNameJTextField.getText();

        if (type == null || enterpriseName.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter enterprise to be added");
            return;
        }

        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree.getLastSelectedPathComponent();
        if (selectedNode != null
                && selectedNode.isRoot() == false
                && selectedNode != networkNode) {

            String networkName = selectedNode.toString();
            Network network = system.getNetworkDirectory().getNetworkInstance(networkName);
            if (network != null) {
                Enterprise e = network.getEnterpriseDirectory().addAndCreateEnterprise(type, enterpriseName, network);
                if (e == null) {
                    JOptionPane.showMessageDialog(null, "Enterprise already exists, you cannot add same enterprise!");
                    return;
                } else {
                    DefaultMutableTreeNode newEnterprise = new DefaultMutableTreeNode(enterpriseName);
                    selectedNode.insert(newEnterprise, 0);
                    enterpriseNameJTextField.setText("");
                    enterpriseJComboBox.setSelectedIndex(0);
                    JOptionPane.showMessageDialog(null, "Enterprise added!");
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Select a network!");
        }
        model.reload();
    }//GEN-LAST:event_addEnterpriseJButtonActionPerformed

    private void removeNetworkJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeNetworkJButtonActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel model = (DefaultTreeModel) jTree.getModel();
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree.getLastSelectedPathComponent();

        if (selectedNode == null
                || selectedNode.isRoot() == true
                || selectedNode == networkNode //|| selectedNode.isNodeAncestor(networkNode.getRoot()) == true
                ) {
            JOptionPane.showMessageDialog(null, "Select a node to be removed and root node cannot be deleted");
        } else {
            String networkName = selectedNode.toString();
            Boolean isNetworkFoundAndRemoved = system.getNetworkDirectory().removeNetwork(networkName);
            if (isNetworkFoundAndRemoved == null
                    || isNetworkFoundAndRemoved == false) {
                JOptionPane.showMessageDialog(null, "Network not found!");
            } else {
                model.removeNodeFromParent(selectedNode);
                JOptionPane.showMessageDialog(null, "Network removed!");
            }
            model.reload();
        }
    }//GEN-LAST:event_removeNetworkJButtonActionPerformed

    private void removeEnterpriseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEnterpriseJButtonActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel model = (DefaultTreeModel) jTree.getModel();

        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree.getLastSelectedPathComponent();

        if (selectedNode == null
                || selectedNode.isRoot() == true
                || selectedNode == networkNode) {
            JOptionPane.showMessageDialog(null, "Select a node to be removed and root node cannot be deleted");
        } else {

            String enterpriseName = selectedNode.toString();
            String networkName = selectedNode.getParent().toString();
            if (!networkName.equals(networkNode.toString())) {
                Network network = system.getNetworkDirectory().getNetworkInstance(networkName);
                Boolean isEnterpriseFoundAndRemoved = network.getEnterpriseDirectory().removeEnterprise(enterpriseName);
                if (isEnterpriseFoundAndRemoved == true) {
                    model.removeNodeFromParent(selectedNode);
                    JOptionPane.showMessageDialog(null, "Enterprise removed!");
                } else {
                    JOptionPane.showMessageDialog(null, "Enterprise not found!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Select an enterprise!");
            }
            model.reload();
        }
    }//GEN-LAST:event_removeEnterpriseJButtonActionPerformed

    private void manageEnterpriseAdminJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEnterpriseAdminJButtonActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseAdminJPanel panel = new ManageEnterpriseAdminJPanel(userProcessContainer, system);
        userProcessContainer.add("ManageEnterpriseAdmin", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEnterpriseAdminJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEnterpriseJButton;
    private javax.swing.JButton addNetworkJButton;
    private javax.swing.JComboBox countryListJComboBox;
    private javax.swing.JComboBox enterpriseJComboBox;
    private javax.swing.JInternalFrame enterpriseJInternalFrame;
    private javax.swing.JLabel enterpriseNameJLabel;
    private javax.swing.JTextField enterpriseNameJTextField;
    private javax.swing.JLabel enterpriseTypeJLabel;
    private javax.swing.JLabel instructionJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree;
    private javax.swing.JButton manageEnterpriseAdminJButton;
    private javax.swing.JInternalFrame networkJInternalFrame;
    private javax.swing.JLabel networkNameJLabel;
    private javax.swing.JLabel panelDescriptionJLabel;
    private javax.swing.JButton removeEnterpriseJButton;
    private javax.swing.JButton removeNetworkJButton;
    // End of variables declaration//GEN-END:variables
}
