/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Sites;

import Business.Enterprise.SiteEnterprise;
import Business.Organization.Organization;
import Business.Organization.Sites.ProviderOrganization;
import Business.Person.Patient;
import Business.Person.Person;
import Business.Person.Provider;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rishika Idnani
 */
public class ManagePatient extends javax.swing.JPanel {

    /**
     * Creates new form ManagePatient
     */
    private JPanel userProcessContainer;
    private SiteEnterprise siteEnterprise;

    public ManagePatient(JPanel userProcessContainer, SiteEnterprise siteEnterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.siteEnterprise = siteEnterprise;
        structureInternalFrame();
        populateJComboBox();
        populteInsuranceOptions();
        populatePatientTable();
    }

    public void populatePatientTable() {
        DefaultTableModel model = (DefaultTableModel) patientJTable.getModel();
        model.setRowCount(0);
        
        for(Person person : siteEnterprise.getPersonDirectory().getPersonList()){
            if(person instanceof Patient){
                Patient patient = (Patient)person;
                Object row[] = new Object[3];
                row[0] = patient;
                row[1] = patient.getPrimaryDoctor();
                row[2] = patient.getInsuranceInformation();
                model.addRow(row);
            }
        }

    }

    public void structureInternalFrame() {
        javax.swing.plaf.InternalFrameUI insuranceFrameUI = insuranceJInternalFrame.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) insuranceFrameUI).setNorthPane(null);

        javax.swing.plaf.InternalFrameUI patientNameFrameUI = patientNameJInternalFrame.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) patientNameFrameUI).setNorthPane(null);

        javax.swing.plaf.InternalFrameUI doctorFrameUI = doctorJInternalFrame.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) doctorFrameUI).setNorthPane(null);
    }

    public void populateJComboBox() {
        doctorJComboBox.removeAllItems();

        for (Organization organization : siteEnterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof ProviderOrganization) {
                ProviderOrganization providerOrganization = (ProviderOrganization) organization;
                for (Person person : providerOrganization.getPersonDirectory().getPersonList()) {
                    if (person instanceof Provider) {
                        Provider provider = (Provider) person;
                        doctorJComboBox.addItem(provider);
                    }
                }
            }
        }
    }

    public void populteInsuranceOptions() {
        insuranceJComboBox.removeAllItems();

        insuranceJComboBox.addItem("Private Insurance Coverage");
        insuranceJComboBox.addItem("Under Insured");
        insuranceJComboBox.addItem("No Insurance");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDescriptionJComboBox = new javax.swing.JLabel();
        patientNameJInternalFrame = new javax.swing.JInternalFrame();
        patientJLabel = new javax.swing.JLabel();
        patientNameJTextField = new javax.swing.JTextField();
        insuranceJInternalFrame = new javax.swing.JInternalFrame();
        insuranceJLabel = new javax.swing.JLabel();
        insuranceJComboBox = new javax.swing.JComboBox();
        insuranceCoverageJLabel = new javax.swing.JLabel();
        coverageJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        doctorJInternalFrame = new javax.swing.JInternalFrame();
        doctorJLabel = new javax.swing.JLabel();
        doctorJComboBox = new javax.swing.JComboBox();
        addPatientJButton = new javax.swing.JButton();
        summaryJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientJTable = new javax.swing.JTable();

        panelDescriptionJComboBox.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelDescriptionJComboBox.setText("Add Patient Information");

        patientNameJInternalFrame.setVisible(true);

        patientJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        patientJLabel.setText("Patient Name:");

        patientNameJTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout patientNameJInternalFrameLayout = new javax.swing.GroupLayout(patientNameJInternalFrame.getContentPane());
        patientNameJInternalFrame.getContentPane().setLayout(patientNameJInternalFrameLayout);
        patientNameJInternalFrameLayout.setHorizontalGroup(
            patientNameJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientNameJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(patientJLabel)
                .addGap(18, 18, 18)
                .addComponent(patientNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        patientNameJInternalFrameLayout.setVerticalGroup(
            patientNameJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientNameJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientNameJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientJLabel)
                    .addComponent(patientNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        insuranceJInternalFrame.setVisible(true);

        insuranceJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        insuranceJLabel.setText("Insurance Information");

        insuranceJComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        insuranceJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        insuranceJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceJComboBoxActionPerformed(evt);
            }
        });

        insuranceCoverageJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        insuranceCoverageJLabel.setText("Insurance coverage(in percentile)");

        coverageJTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        coverageJTextField.setEnabled(false);

        javax.swing.GroupLayout insuranceJInternalFrameLayout = new javax.swing.GroupLayout(insuranceJInternalFrame.getContentPane());
        insuranceJInternalFrame.getContentPane().setLayout(insuranceJInternalFrameLayout);
        insuranceJInternalFrameLayout.setHorizontalGroup(
            insuranceJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insuranceJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insuranceJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insuranceJLabel)
                    .addComponent(insuranceCoverageJLabel)
                    .addComponent(coverageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insuranceJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        insuranceJInternalFrameLayout.setVerticalGroup(
            insuranceJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insuranceJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insuranceJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(insuranceJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(insuranceCoverageJLabel)
                .addGap(18, 18, 18)
                .addComponent(coverageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        backJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        doctorJInternalFrame.setVisible(true);

        doctorJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        doctorJLabel.setText("Primary Doctor:");

        doctorJComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        doctorJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout doctorJInternalFrameLayout = new javax.swing.GroupLayout(doctorJInternalFrame.getContentPane());
        doctorJInternalFrame.getContentPane().setLayout(doctorJInternalFrameLayout);
        doctorJInternalFrameLayout.setHorizontalGroup(
            doctorJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(doctorJLabel)
                .addGap(18, 18, 18)
                .addComponent(doctorJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        doctorJInternalFrameLayout.setVerticalGroup(
            doctorJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorJInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(doctorJInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorJLabel)
                    .addComponent(doctorJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addPatientJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addPatientJButton.setText("Add Patient");
        addPatientJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientJButtonActionPerformed(evt);
            }
        });

        summaryJLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        summaryJLabel.setText("Summary of Patients");

        patientJTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        patientJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Patient Name", "Assigned Doctor", "Insurance Information"
            }
        ));
        patientJTable.setRowHeight(25);
        jScrollPane1.setViewportView(patientJTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelDescriptionJComboBox)
                            .addComponent(summaryJLabel)
                            .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(patientNameJInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(doctorJInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(insuranceJInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(addPatientJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 151, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDescriptionJComboBox)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(patientNameJInternalFrame)
                            .addComponent(doctorJInternalFrame)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(addPatientJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insuranceJInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(summaryJLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(backJButton)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addPatientJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientJButtonActionPerformed
        // TODO add your handling code here:
        String name = patientNameJTextField.getText();

        if (name.equals("")) {
            JOptionPane.showMessageDialog(null, "Kindly input the patient name!");
            return;
        }

        String insuranceInformation = String.valueOf(insuranceJComboBox.getSelectedItem());
        Provider provider = (Provider) doctorJComboBox.getSelectedItem();
        Patient patient = siteEnterprise.getPersonDirectory().addAndCreatePatient(name);
        if (patient == null) {
            JOptionPane.showMessageDialog(null, "Patient already exists!!");
            return;
        }
        provider.getPatientList().add(patient);
        patient.setPrimaryDoctor(provider);
        patient.setInsuranceInformation(insuranceInformation);
        if (insuranceInformation.equals("Under Insured")) {
            float coveragePercentile;
            try {
                coveragePercentile = Float.parseFloat(coverageJTextField.getText());
                if (coveragePercentile <= 0 || coveragePercentile >= 100) {
                    throw new Exception();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Insert proper values");
                return;
            }
            patient.setCoveragePercentile(coveragePercentile);
        }
        patientNameJTextField.setText("");
        doctorJComboBox.setSelectedIndex(0);
        insuranceJComboBox.setSelectedIndex(0);
        coverageJTextField.setText("");
        populatePatientTable();
    }//GEN-LAST:event_addPatientJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void insuranceJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceJComboBoxActionPerformed
        // TODO add your handling code here:
        String insuranceInfo = String.valueOf(insuranceJComboBox.getSelectedItem());

        if (insuranceInfo.equals("Under Insured")) {
            coverageJTextField.setEnabled(true);
        } else {
            coverageJTextField.setEnabled(false);
        }
    }//GEN-LAST:event_insuranceJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPatientJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField coverageJTextField;
    private javax.swing.JComboBox doctorJComboBox;
    private javax.swing.JInternalFrame doctorJInternalFrame;
    private javax.swing.JLabel doctorJLabel;
    private javax.swing.JLabel insuranceCoverageJLabel;
    private javax.swing.JComboBox insuranceJComboBox;
    private javax.swing.JInternalFrame insuranceJInternalFrame;
    private javax.swing.JLabel insuranceJLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel panelDescriptionJComboBox;
    private javax.swing.JLabel patientJLabel;
    private javax.swing.JTable patientJTable;
    private javax.swing.JInternalFrame patientNameJInternalFrame;
    private javax.swing.JTextField patientNameJTextField;
    private javax.swing.JLabel summaryJLabel;
    // End of variables declaration//GEN-END:variables
}
