/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Sites;

import Business.Enterprise.Enterprise;
import Business.Enterprise.SiteEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.Sites.ProviderOrganization;
import Business.Person.Person;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import static com.sun.webkit.perf.WCGraphicsPerfLogger.reset;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rishika Idnani
 */
public class ManageSiteOrganizationAccount extends javax.swing.JPanel {

    /**
     * Creates new form ManageSiteOrganizationAccount
     */
    private JPanel userProcessContainer;
    private SiteEnterprise siteEnterprise;
    private Network network;

    public ManageSiteOrganizationAccount(JPanel userProcessContainer, SiteEnterprise siteEnterprise, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.siteEnterprise = siteEnterprise;
        this.network = network;

        populateOrganizationComboBox();
        populateUserAccountTable();
    }

    public void populateOrganizationComboBox() {
        organizationJComboBox.removeAllItems();

        for (Organization o : siteEnterprise.getOrganizationDirectory().getOrganizationList()) {
            organizationJComboBox.addItem(o);
        }
    }

    public void populateRoleComboBox(Organization o) {
        roleJComboBox.removeAllItems();

        for (Role role : o.getSupportedRole()) {
            roleJComboBox.addItem(role);
        }
    }

    public void populateUserAccountTable() {
        DefaultTableModel model = (DefaultTableModel) userAccountJTable.getModel();
        model.setRowCount(0);

        //Network network = enterprise.getNetwork();
        for (Organization o : siteEnterprise.getOrganizationDirectory().getOrganizationList()) {

            for (UserAccount ua : o.getUserAccountDirectory().getUserAccountList()) {
                Object row[] = new Object[2];
                row[0] = o;
                row[1] = ua;
                model.addRow(row);
            }
        }
    }

    public void reset() {
        personNameJTextField.setText("");
        userNameJTextField.setText("");
        passwordJPasswordField.setText("");
        confirmPasswordJPasswordField.setText("");
        organizationJComboBox.setSelectedIndex(0);
        roleJComboBox.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordJPasswordField = new javax.swing.JPasswordField();
        userNameJTextField = new javax.swing.JTextField();
        addUserAccountJLabel = new javax.swing.JLabel();
        roleJComboBox = new javax.swing.JComboBox();
        personNameJTextField = new javax.swing.JTextField();
        confirmPasswordJLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        resetJButton2 = new javax.swing.JButton();
        organizationJLabel = new javax.swing.JLabel();
        removeJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userAccountJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        submitJButton = new javax.swing.JButton();
        userNameJLabel = new javax.swing.JLabel();
        function2JLabel = new javax.swing.JLabel();
        passwordJLabel = new javax.swing.JLabel();
        panelDescriptionJLabel = new javax.swing.JLabel();
        organizationJComboBox = new javax.swing.JComboBox();
        chooseOJLabel = new javax.swing.JLabel();
        confirmPasswordJPasswordField = new javax.swing.JPasswordField();
        roleJLabel = new javax.swing.JLabel();
        personNameJLabel = new javax.swing.JLabel();

        addUserAccountJLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        addUserAccountJLabel.setText("Add User Account");

        roleJComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        roleJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        confirmPasswordJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        confirmPasswordJLabel.setText("Confirm Password");

        backJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        resetJButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        resetJButton2.setText("Reset");
        resetJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetJButton2ActionPerformed(evt);
            }
        });

        organizationJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        organizationJLabel.setText("Organization");

        removeJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        removeJButton.setText("Remove User Account");
        removeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJButtonActionPerformed(evt);
            }
        });

        userAccountJTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        userAccountJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Organization name", "User Name"
            }
        ));
        jScrollPane1.setViewportView(userAccountJTable);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Add Person");

        submitJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        userNameJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        userNameJLabel.setText("User Name");

        function2JLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        function2JLabel.setText("Display of created User Accounts");

        passwordJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        passwordJLabel.setText("Password");

        panelDescriptionJLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelDescriptionJLabel.setText("Manage Site Organization Account");

        organizationJComboBox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        organizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        organizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationJComboBoxActionPerformed(evt);
            }
        });

        chooseOJLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        chooseOJLabel.setText("Choose Organization");

        roleJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        roleJLabel.setText("Role");

        personNameJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        personNameJLabel.setText("Person Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeJButton))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(function2JLabel)
                            .addComponent(panelDescriptionJLabel)
                            .addComponent(chooseOJLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(organizationJLabel)
                                        .addGap(52, 52, 52)
                                        .addComponent(organizationJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(personNameJLabel)
                                        .addGap(44, 44, 44)
                                        .addComponent(personNameJTextField))))
                            .addComponent(addUserAccountJLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resetJButton2)
                                .addGap(212, 212, 212)
                                .addComponent(submitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordJLabel)
                                    .addComponent(confirmPasswordJLabel)
                                    .addComponent(roleJLabel)
                                    .addComponent(userNameJLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(passwordJPasswordField)
                                    .addComponent(roleJComboBox, 0, 170, Short.MAX_VALUE)
                                    .addComponent(confirmPasswordJPasswordField)
                                    .addComponent(userNameJTextField))))
                        .addGap(248, 422, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDescriptionJLabel)
                .addGap(26, 26, 26)
                .addComponent(chooseOJLabel)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organizationJLabel)
                    .addComponent(organizationJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(personNameJLabel)
                            .addComponent(personNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(addUserAccountJLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameJLabel)
                    .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordJLabel)
                    .addComponent(passwordJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPasswordJLabel)
                    .addComponent(confirmPasswordJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleJLabel)
                    .addComponent(roleJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetJButton2)
                    .addComponent(submitJButton))
                .addGap(24, 24, 24)
                .addComponent(function2JLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeJButton)
                    .addComponent(backJButton))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void resetJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetJButton2ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_resetJButton2ActionPerformed

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = userAccountJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select a row to be deleted!");
            return;
        }

        Organization o = (Organization) userAccountJTable.getValueAt(selectedRow, 0);
        UserAccount userAccount = (UserAccount) userAccountJTable.getValueAt(selectedRow, 1);
        
        Person person = userAccount.getPerson();
        o.getPersonDirectory().removePerson(person);
        o.getUserAccountDirectory().removeUserAccount(userAccount);
        populateUserAccountTable();
    }//GEN-LAST:event_removeJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        // TODO add your handling code here:
        Organization o = (Organization) organizationJComboBox.getSelectedItem();

        String userName = userNameJTextField.getText();
        String password = String.valueOf(passwordJPasswordField.getPassword());
        String confirmPassword = String.valueOf(confirmPasswordJPasswordField.getPassword());
        Role role = (Role) roleJComboBox.getSelectedItem();
        String personName = personNameJTextField.getText();

        if (personName.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter the name!");
            return;
        }

        if (userName.trim().equals("")
                || password.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Kindly fill proper inputs!");
            return;
        }

        if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(null, "Password does not match!");
            return;
        }
//Check at the enterprise level            
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            Boolean isUserNameUsed = enterprise.getUserAccountDirectory().checkUserAccountAvailability(userName);
            if (isUserNameUsed == true) {
                JOptionPane.showMessageDialog(null, "User Name Already in use!");
                return;
            }
        }

//Check at the organization level            
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                Boolean isUserNameUsed = org.getUserAccountDirectory().checkUserAccountAvailability(userName);
                if (isUserNameUsed == true) {
                    JOptionPane.showMessageDialog(null, "User Name Already in use!");
                    return;
                }
            }
        }

        Organization org = (Organization) organizationJComboBox.getSelectedItem();
        Person person = null;
        if (o instanceof ProviderOrganization) {
            person = org.getPersonDirectory().addAndCreateProvider(personName);
        } else {
            person = org.getPersonDirectory().addAndCreatePerson(personName);
        }
        org.getUserAccountDirectory().createAndAddUserAccount(userName, password, role, person);
        populateUserAccountTable();
        reset();
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJComboBoxActionPerformed
        // TODO add your handling code here:
        Organization o = (Organization) organizationJComboBox.getSelectedItem();

        if (o != null) {
            populateRoleComboBox(o);
        }
    }//GEN-LAST:event_organizationJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addUserAccountJLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel chooseOJLabel;
    private javax.swing.JLabel confirmPasswordJLabel;
    private javax.swing.JPasswordField confirmPasswordJPasswordField;
    private javax.swing.JLabel function2JLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JLabel organizationJLabel;
    private javax.swing.JLabel panelDescriptionJLabel;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JPasswordField passwordJPasswordField;
    private javax.swing.JLabel personNameJLabel;
    private javax.swing.JTextField personNameJTextField;
    private javax.swing.JButton removeJButton;
    private javax.swing.JButton resetJButton2;
    private javax.swing.JComboBox roleJComboBox;
    private javax.swing.JLabel roleJLabel;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTable userAccountJTable;
    private javax.swing.JLabel userNameJLabel;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
