/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Sites;

import Business.Enterprise.CDCEnterprise;
import Business.Enterprise.NationalDistributorEnterprise;
import Business.Enterprise.SiteEnterprise;
import Business.Organization.Sites.ProviderOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Rishika Idnani
 */
public class ProviderWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form ProviderWorkArea
     */
    private JPanel userProcessContainer;
    private ProviderOrganization providerOrganization;
    private CDCEnterprise cdcEnterprise;
    private SiteEnterprise siteEnterprise;
    private UserAccount userAccount;
    private NationalDistributorEnterprise nationalDistributor;

    public ProviderWorkArea(JPanel userProcessContainer, ProviderOrganization providerOrganization,
            CDCEnterprise cdcEnterprise, SiteEnterprise siteEnterprise, UserAccount userAccount, NationalDistributorEnterprise nationalDistributor) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.providerOrganization = providerOrganization;
        this.cdcEnterprise = cdcEnterprise;
        this.siteEnterprise = siteEnterprise;
        this.userAccount = userAccount;
        this.nationalDistributor = nationalDistributor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDescriptionJLabel = new javax.swing.JLabel();
        orderVaccineJButton = new javax.swing.JButton();
        viewJButton = new javax.swing.JButton();
        managePatientBillsJButton = new javax.swing.JButton();
        viewBillsJButton = new javax.swing.JButton();
        viewAlertsJButton = new javax.swing.JButton();

        panelDescriptionJLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelDescriptionJLabel.setText("Provider Work Area");

        orderVaccineJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        orderVaccineJButton.setText("Order Vaccines >>");
        orderVaccineJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderVaccineJButtonActionPerformed(evt);
            }
        });

        viewJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        viewJButton.setText("View Orders >>");
        viewJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewJButtonActionPerformed(evt);
            }
        });

        managePatientBillsJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        managePatientBillsJButton.setText("Manage Patient Bills >>");
        managePatientBillsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePatientBillsJButtonActionPerformed(evt);
            }
        });

        viewBillsJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        viewBillsJButton.setText("View Bills >>");
        viewBillsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBillsJButtonActionPerformed(evt);
            }
        });

        viewAlertsJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        viewAlertsJButton.setText("View Alerts regarding Vaccine >>");
        viewAlertsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAlertsJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(managePatientBillsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(panelDescriptionJLabel))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(158, 158, 158)
                            .addComponent(orderVaccineJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(viewAlertsJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewBillsJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDescriptionJLabel)
                .addGap(27, 27, 27)
                .addComponent(orderVaccineJButton)
                .addGap(18, 18, 18)
                .addComponent(viewJButton)
                .addGap(18, 18, 18)
                .addComponent(managePatientBillsJButton)
                .addGap(18, 18, 18)
                .addComponent(viewBillsJButton)
                .addGap(18, 18, 18)
                .addComponent(viewAlertsJButton)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void orderVaccineJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderVaccineJButtonActionPerformed
        // TODO add your handling code here:
        OrderVaccineJPanel panel = new OrderVaccineJPanel(userProcessContainer, cdcEnterprise, siteEnterprise, providerOrganization, userAccount);

        userProcessContainer.add("OrderVaccine", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_orderVaccineJButtonActionPerformed

    private void viewJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewJButtonActionPerformed
        // TODO add your handling code here:
        ViewMyOrders panel = new ViewMyOrders(userProcessContainer, cdcEnterprise, siteEnterprise, providerOrganization, userAccount);

        userProcessContainer.add("ViewMyOrders", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewJButtonActionPerformed

    private void viewBillsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBillsJButtonActionPerformed
        // TODO add your handling code here:
        ViewBills panel = new ViewBills(userProcessContainer, providerOrganization, cdcEnterprise, siteEnterprise, userAccount, nationalDistributor);

        userProcessContainer.add("ViewBills", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewBillsJButtonActionPerformed

    private void managePatientBillsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePatientBillsJButtonActionPerformed
        // TODO add your handling code here:
        ManagePatientBills panel = new ManagePatientBills(userProcessContainer, providerOrganization, cdcEnterprise, siteEnterprise, userAccount);

        userProcessContainer.add("ManagePatientBills", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePatientBillsJButtonActionPerformed

    private void viewAlertsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAlertsJButtonActionPerformed
        // TODO add your handling code here:
        ViewVaccineAlerts panel = new ViewVaccineAlerts(userProcessContainer, providerOrganization, cdcEnterprise, siteEnterprise, userAccount, nationalDistributor);

        userProcessContainer.add("ManagePatientBills", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewAlertsJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton managePatientBillsJButton;
    private javax.swing.JButton orderVaccineJButton;
    private javax.swing.JLabel panelDescriptionJLabel;
    private javax.swing.JButton viewAlertsJButton;
    private javax.swing.JButton viewBillsJButton;
    private javax.swing.JButton viewJButton;
    // End of variables declaration//GEN-END:variables
}
