/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Sites;

import Business.Enterprise.CDCEnterprise;
import Business.Enterprise.SiteEnterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Rishika Idnani
 */
public class SiteWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form SiteWorkArea
     */
    private JPanel userProcessContainer;
    private CDCEnterprise cdcEnterprise;
    private SiteEnterprise siteEnterprise;
    private Network network;

    public SiteWorkArea(JPanel userProcessContainer, CDCEnterprise cdcEnterprise, SiteEnterprise siteEnterprise, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.cdcEnterprise = cdcEnterprise;
        this.siteEnterprise = siteEnterprise;
        this.network = network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDescriptionJLabel = new javax.swing.JLabel();
        manageAccountJButton = new javax.swing.JButton();
        manageOrganizationJButton = new javax.swing.JButton();
        managePatientJButton = new javax.swing.JButton();

        panelDescriptionJLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelDescriptionJLabel.setText("Site Work Area");

        manageAccountJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        manageAccountJButton.setText("Manage Organization User Accounts >>");
        manageAccountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAccountJButtonActionPerformed(evt);
            }
        });

        manageOrganizationJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        manageOrganizationJButton.setText("Manage Organizations >>");
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });

        managePatientJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        managePatientJButton.setText("Manage Patients and Accounts >>");
        managePatientJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePatientJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDescriptionJLabel)
                    .addComponent(manageAccountJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageOrganizationJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(managePatientJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(396, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDescriptionJLabel)
                .addGap(30, 30, 30)
                .addComponent(manageOrganizationJButton)
                .addGap(18, 18, 18)
                .addComponent(manageAccountJButton)
                .addGap(18, 18, 18)
                .addComponent(managePatientJButton)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageAccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAccountJButtonActionPerformed
        // TODO add your handling code here:
        ManageSiteOrganizationAccount panel = new ManageSiteOrganizationAccount(userProcessContainer, siteEnterprise, network);

        userProcessContainer.add("ManageSiteOrgAccounts", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageAccountJButtonActionPerformed

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed
        // TODO add your handling code here:
        ManageOrganization panel = new ManageOrganization(userProcessContainer, cdcEnterprise, siteEnterprise);

        userProcessContainer.add("ManageOrganizations", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void managePatientJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePatientJButtonActionPerformed
        // TODO add your handling code here:
        ManagePatient panel = new ManagePatient(userProcessContainer, siteEnterprise);

        userProcessContainer.add("ManagePatient", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePatientJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton manageAccountJButton;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JButton managePatientJButton;
    private javax.swing.JLabel panelDescriptionJLabel;
    // End of variables declaration//GEN-END:variables
}
