/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Sites;

import Business.Enterprise.CDCEnterprise;
import Business.Enterprise.NationalDistributorEnterprise;
import Business.Enterprise.SiteEnterprise;
import Business.Enterprise.VaccineManufacturerEnterprise;
import Business.Order.Order;
import Business.Order.OrderItem;
import Business.Organization.Distributor.DistributionCentre;
import Business.Organization.Organization;
import Business.Organization.Sites.ProviderOrganization;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.BillTheProvider;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rishika Idnani
 */
public class ViewBills extends javax.swing.JPanel {

    /**
     * Creates new form ViewBills
     */
    private JPanel userProcessContainer;
    private ProviderOrganization providerOrganization;
    private CDCEnterprise cdcEnterprise;
    private SiteEnterprise siteEnterprise;
    private UserAccount userAccount;
    private NationalDistributorEnterprise nationalDistributor;

    public ViewBills(JPanel userProcessContainer, ProviderOrganization providerOrganization,
            CDCEnterprise cdcEnterprise, SiteEnterprise siteEnterprise, UserAccount userAccount, NationalDistributorEnterprise nationalDistributor) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.providerOrganization = providerOrganization;
        this.cdcEnterprise = cdcEnterprise;
        this.siteEnterprise = siteEnterprise;
        this.userAccount = userAccount;
        this.nationalDistributor = nationalDistributor;
        populateOrderList();
    }

    public void populateOrderList() {
        DefaultListModel model = new DefaultListModel();
        manufacturerJList.removeAll();

        for (Organization organization : nationalDistributor.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof DistributionCentre) {
                DistributionCentre dc = (DistributionCentre) organization;
                for (WorkRequest w : dc.getWorkQueue().getWorkRequestList()) {
                    if (w instanceof BillTheProvider) {
                        BillTheProvider workRequest = (BillTheProvider) w;
                        Boolean isPresent = false;
                        for (int i = 0; i < manufacturerJList.getModel().getSize(); i++) {
                            if (manufacturerJList.getModel().getElementAt(i) == workRequest.getOrder()) {
                                isPresent = true;
                                break;
                            }
                        }
                        if (isPresent == false) {
                            Person person = workRequest.getOrder().getProvider();
                            if (person == userAccount.getPerson()) {
                                for (OrderItem oi : workRequest.getOrder().getOrderItemList()) {
                                    if (oi.getIfPaid().equals("Pending")) {
                                        model.addElement(workRequest.getOrder());
                                        break;
                                    }
                                }
                            }
                        }
                        manufacturerJList.setModel(model);
                    }
                }
            }
        }
    }

    public void populateTable(Order order) {
        double totalPrice = 0;

        DefaultTableModel model = (DefaultTableModel) billJTable.getModel();
        model.setRowCount(0);
        for (OrderItem oi : order.getOrderItemList()) {
            if (oi.getIsOrderItemShippedToSite().equals("Approved") && oi.getIfPaid().equals("Pending")) {
                Object row[] = new Object[3];
                row[0] = oi;
                row[1] = oi.getVaccine().getDisease();
                row[2] = (6.25 / 100) * oi.getTotalPrice() + oi.getTotalPrice();
                totalPrice = totalPrice + ((6.25 / 100) * oi.getTotalPrice()) + oi.getTotalPrice();
                model.addRow(row);
            }
        }
        totalJTextField.setText(String.valueOf(totalPrice));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDescriptionJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        billJTable = new javax.swing.JTable();
        backJButton2 = new javax.swing.JButton();
        selectJLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        manufacturerJList = new javax.swing.JList();
        viewJLabel = new javax.swing.JLabel();
        clickHereJButton = new javax.swing.JButton();
        totalJLabel = new javax.swing.JLabel();
        totalJTextField = new javax.swing.JTextField();
        dollarJLabel = new javax.swing.JLabel();
        paidJButton = new javax.swing.JButton();

        panelDescriptionJLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelDescriptionJLabel.setText("View Bills");

        billJTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        billJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Vaccine Name", "Disease", "Total Invoice"
            }
        ));
        billJTable.setRowHeight(25);
        jScrollPane1.setViewportView(billJTable);

        backJButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        backJButton2.setText("<< Back");
        backJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton2ActionPerformed(evt);
            }
        });

        selectJLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        selectJLabel.setText("Select a Vaccine manufacturer:");

        jScrollPane2.setViewportView(manufacturerJList);

        viewJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        viewJLabel.setText("View details of ordered items from the manufacturer");

        clickHereJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        clickHereJButton.setText("Click here!");
        clickHereJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickHereJButtonActionPerformed(evt);
            }
        });

        totalJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        totalJLabel.setText("Total Amount");

        totalJTextField.setEditable(false);
        totalJTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        totalJTextField.setEnabled(false);

        dollarJLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        dollarJLabel.setText("$");

        paidJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        paidJButton.setText("Paid");
        paidJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(panelDescriptionJLabel)
                                .addComponent(selectJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(viewJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clickHereJButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 506, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(paidJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalJLabel)
                        .addGap(24, 24, 24)
                        .addComponent(totalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dollarJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDescriptionJLabel)
                .addGap(18, 18, 18)
                .addComponent(selectJLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewJLabel)
                    .addComponent(clickHereJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalJLabel)
                    .addComponent(totalJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dollarJLabel)
                    .addComponent(paidJButton))
                .addGap(25, 25, 25)
                .addComponent(backJButton2)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton2ActionPerformed

    private void clickHereJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickHereJButtonActionPerformed
        // TODO add your handling code here:
        int selectedIndex = manufacturerJList.getSelectedIndex();

        if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(null, "Kindly select a Vaccine Manufacturer!");
            return;
        }
        Order order = (Order) manufacturerJList.getSelectedValue();
        populateTable(order);
    }//GEN-LAST:event_clickHereJButtonActionPerformed

    private void paidJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidJButtonActionPerformed
        // TODO add your handling code here:

        int selectedRow = billJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select a row!");
            return;
        }

        OrderItem orderItem = (OrderItem) billJTable.getValueAt(selectedRow, 0);
        orderItem.setIfPaid("Paid");

        int selectedIndex = manufacturerJList.getSelectedIndex();

        if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(null, "Kindly select a Vaccine Manufacturer!");
            return;
        }
        Order order = (Order) manufacturerJList.getSelectedValue();

//        VaccineManufacturerEnterprise manufacturer = (VaccineManufacturerEnterprise) manufacturerJList.getSelectedValue();
        populateOrderList();
        populateTable(order);
    }//GEN-LAST:event_paidJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton2;
    private javax.swing.JTable billJTable;
    private javax.swing.JButton clickHereJButton;
    private javax.swing.JLabel dollarJLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList manufacturerJList;
    private javax.swing.JButton paidJButton;
    private javax.swing.JLabel panelDescriptionJLabel;
    private javax.swing.JLabel selectJLabel;
    private javax.swing.JLabel totalJLabel;
    private javax.swing.JTextField totalJTextField;
    private javax.swing.JLabel viewJLabel;
    // End of variables declaration//GEN-END:variables
}
