/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Sites;

import Business.Enterprise.CDCEnterprise;
import Business.Enterprise.NationalDistributorEnterprise;
import Business.Enterprise.SiteEnterprise;
import Business.Order.Order;
import Business.Order.OrderItem;
import Business.Organization.CDC.CDCOperationsOrganization;
import Business.Organization.Organization;
import Business.Organization.Sites.ProviderOrganization;
import Business.Person.Provider;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.InformBadVaccineToSites;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rishika Idnani
 */
public class ViewVaccineAlerts extends javax.swing.JPanel {

    /**
     * Creates new form ViewVaccineAlerts
     */
    private JPanel userProcessContainer;
    private ProviderOrganization providerOrganization;
    private CDCEnterprise cdcEnterprise;
    private SiteEnterprise siteEnterprise;
    private UserAccount userAccount;
    private NationalDistributorEnterprise nationalDistributor;
    private Date manufacturingBatch;

    public ViewVaccineAlerts(JPanel userProcessContainer, ProviderOrganization providerOrganization,
            CDCEnterprise cdcEnterprise, SiteEnterprise siteEnterprise, UserAccount userAccount, NationalDistributorEnterprise nationalDistributor) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.providerOrganization = providerOrganization;
        this.cdcEnterprise = cdcEnterprise;
        this.siteEnterprise = siteEnterprise;
        this.userAccount = userAccount;
        this.nationalDistributor = nationalDistributor;

        populateVaccineTable();
    }

    public void populateVaccineTable() {
        DefaultTableModel model = (DefaultTableModel) alertJTable.getModel();
        model.setRowCount(0);

        for (Organization organization : cdcEnterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof CDCOperationsOrganization) {
                CDCOperationsOrganization cdcOrganization = (CDCOperationsOrganization) organization;
                for (WorkRequest workRequest : cdcOrganization.getWorkQueue().getWorkRequestList()) {
                    if (workRequest instanceof InformBadVaccineToSites) {
                        InformBadVaccineToSites request = (InformBadVaccineToSites) workRequest;
                        manufacturingBatch = request.getOrderItem().getManufacturingBatch();
                        Provider provider = (Provider) userAccount.getPerson();
                        for (Order order : provider.getOrderedList()) {
                            for (OrderItem oi : order.getOrderItemList()) {
                                if (oi.getManufacturingBatch() == manufacturingBatch) {
                                    Object row[] = new Object[4];
                                    row[0] = oi.getVaccine();
                                    row[1] = oi.getManufacturingBatch();
                                    row[2] = oi.getTotalQuantity();
                                    row[3] = request;
                                    model.addRow(row);
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDescriptionJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alertJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();

        panelDescriptionJLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelDescriptionJLabel.setText("Vaccine Alerts");

        alertJTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        alertJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Vaccine Name", "Batch Number", "Quantity", "Note"
            }
        ));
        alertJTable.setRowHeight(25);
        jScrollPane1.setViewportView(alertJTable);

        backJButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelDescriptionJLabel)
                            .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDescriptionJLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(backJButton)
                .addContainerGap(156, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable alertJTable;
    private javax.swing.JButton backJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel panelDescriptionJLabel;
    // End of variables declaration//GEN-END:variables
}
